### ISSUE TITLE
Textual tag enhancements and a minor bug

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#101]
First of all thanks alot for the textual tags.
And may I suggest the following enhancements:
1. When searching it would be better to see the list of tags in the lower pannel, so one can type a couple of letters and the tags caontaining it start to get highlighted  then he choses what he wants.
2. Also when typing new tag, that would be very helpful to see any tags containing the letters one types
This feature is already in WetHat's tagging kit here in Github.
3. The third and more important one is tag hierarchy, like Evernote tags. The relation between father and child tags could be using '/' or '.' . I dont' recommend the dash or underscore, as lots of people use those in naming their tags.
The bug:
Recently used tags doesn't work.
Thanks again for the great work.
P.S. I've been using WetHat's tagging kit for a while and have lots of tags there (about 300 and counting). Should I continue using it or switch to yours (after you add the enhancments, especially the tag hierarchy)? If so I would need a safe way to move the tags.

**Comment by stevencohn** [comment]
For 1, when you type a tag, the tags in the lower panel do get highlighted, but not as partial tags are typed, only after you've entered an entire tag. I may or may not enhance this.

The intention is not to duplicate WetHat's tagging system; it's based on facetted searching and, while that's cool and demo's nicely, in the real world, serves little practical purpose. The main goal is to find related pages and do something with them.

No. I don't care for tag hierarchies. The primary tenet of OneMore is to provide "simple yet powerful" features. Tag hierarchy are over-engineering in my opinion.

Recently used tags does work. It will show tags from (up to) the last 20 tagged pages that were modified.

P.S. I 100% guarantee that I will not provide a migration path from WetHat's tagging to OneMore tagging. I will also not be separating every arbitrary tag into a distinct OneNote tag like WetHat does since I think that overly complicates the cognitive dissonance of not only that feature but OneNote's bulit-in tagging feature as well.

**Comment by stevencohn** [comment]
Just an update, I still haven't noticed any issues with the _recently used tags_ feature. If you have a repeatable example, I could look into it

**Comment by osman1963** [comment]
First of all, thanks for your great efforts and for clarifying the purpose
and nature of OneMore tagging system. In fact, after understanding it I
found out it might be one of the few features of OneMore I won't be using
as I have other purposes when using tags, which are already met by the one
I'm using now, except for the hierarchy thing, which is a great plus, but
not a deal breaker for me.
That being said, I believe I can't provide you with an example of the
'recently used tags', as I switched back to my old tagging system.
Once again, thanks for your great addon.. keep it up :)
