### ISSUE TITLE
Arrange Containers Modification

### ISSUE THREAD

**Issue by ChaosOrdeal** [stevencohn/OneMore#1024]
# Problem to Solve

OneNote is resistant to container organization.

# New Feature/Solution

I suppose this are two related feature requests, really:

1. This is a modification to a feature (that I originally requested -- thanks!).  Using the current Arrange Containers feature, all containers can be organized into a single column.  This seems to work fine, but, personally I find that the containers are a bit too far apart (up and down).  Could there be an option to make these colser or farther apart?  This is one of the missing features of OneNote that really baffles and frustrates me.

2. When the columns feature is used, rather than arranging the page into a grid, could the containers be split into releatively equal-length columns (without changing the order), then each column stacked as it is when using the first Arrange Containers feature (with a new option for them to be closer/farther like in point 1 above).  Basically, the point is to make columns of containers like you would see paragraphs on a newspaper page, not a grid like an Excel spreadsheet.

The hope is that I could just go to ANY OneNote page, click one of these options, and my page is neat, top-aligned, in columns (if I choose that option), without big gaps, no containers floating about, nor some stray containers way away from other containers.  I would like the re-organization to respect the user's container order, but when containers are in oddball positions "order" may not mean much -- a best-guess at order is fine.  Best guess is better than the current system of "do this all manually."

**Comment by akadormouse** [comment]
Managing containers seems to be a major weakness in OneNote.
I'd simply like to bring a container into focus, in the way many apps allow notes to be focused, but have entirely failed to find a way of doing so. For me, it makes OneNote unusable for substantive notes.

**Comment by akadormouse** [comment]
> I'm guessing you have _large pages_ on which you've arranged multiple containers and want to pan around the page to see different containers. Are you asking for something like a list of containers (maybe identified by the first line or two of text) and be able to scroll to that container? (This is not a statement of intent, just a query to understand!)
> 
`I'm guessing you have large pages on which you've arranged multiple containers and want to pan around the page to see different containers. Are you asking for something like a list of containers (maybe identified by the first line or two of text) and be able to scroll to that container? (This is not a statement of intent, just a query to understand!)`

What I'd like would be the equivalent of a focus mode as seen in most note-taking and writing apps - Obsidian, FocusWriter, Scrivener etc - where a note can be made fullscreen, so that only the text of that note is visible. In OneNote, the equivalent F11 focuses on the page which doesn't help much when there are multiple containers on a page. I assume that OneNote regards a page as the note, in which case there's much less value in seeing it as a whiteboard with multiple notes

**Comment by stevencohn** [comment]
Yes. That's correct. The way I think of it is that a container is a way of emulating a sticky note on a whiteboard. You can only write on sticky notes but you can move them around. But there is no way of focusing on just one sticky note (container) at a time.

**Comment by akadormouse** [comment]
Sad. Heptabase, Scrintal, Canvas et al are free to develop the market entirely based on the idea of notes on a whiteboard. But with Hepta and Scrintal being databases, you're either all in or there's high friction. Never mind :(
