### ISSUE TITLE
AddIn not listed in COM-Add-Ins for domain account

### ISSUE THREAD

**Issue by kaltokri** [stevencohn/OneMore#1041]
# Problem to Solve
AddIn is only configured in local administrator account.
My domain account has no local admin rights. But there is a local account with admin rights and I know the password to use it.

# To Reproduce

1. Install with runas command described in documentation
2. Open File / Options / AddIns / COM-Add-Ins / Go as domain user = no entry
3. Open File / Options / AddIns / COM-Add-Ins / Go as local admin = OneMore is listed, activated and can be used

I tried to reinstall it, logout + login, reboot etc. No change.

Is there a way to add the Add-In manually for the domain user?

# Expected Behavior

Installer work for domain user, too.

# Environment (if applicable)

 - OneNote Version: O365 2304 64 Bit
 - Windows 10 Pro 22H2 64 Bit
 - Installer used OneMore_5.8.4_Setupx64.msi

# Additional Context

%localappdata%\temp\OneMore.log in not generated, because OneNote doesn't load the AddIn at all.

**Comment by jasonjac2** [comment]
That's interesting as a lot of installers ask "just for you or for all users".

**Comment by stevencohn** [comment]
I do not believe this is a defect in OneMore or its setup. I suspect it's due to your corporate policy blocking scripts or executables from running during login for your domain account.

When OneMore is installed, it creates a Windows "Active Setup" entry in the Registry. This is a standard, built-in Windows feature. When a user logs in, it checks this entry for things to do and, if it hasn't done them before, performs the action one-time. For OneMore, this means applying the necessary Registry settings to register the add-in with OneNote. Specifically, it reruns the OneMore installer with a parameter that only touches the Registry for the user; it presumes OneMore is otherwise installed on the system.

This Active Setup approach is ideal for this use case because it allows admin-like access to the Registry. Otherwise, since you're domain account doesn't have this permission, there's no way to manually registry the add-in.

So I would check with your IT department to ask if they're blocking Active Setup on your machines.
