### ISSUE TITLE
How does OneMore save it tags?

### ISSUE THREAD

**Issue by seaspeak** [stevencohn/OneMore#1066]
Adding a Tag will add a Note Container with that tag which is compatible with OneNote tag system. And It seems:
- removing the Container won't remove the real tag. But
- removing the whole page will remove the tag and so does the one in Suggestions|Recently Used.

It is good to know OneMore saves the tags in a concealed way so that tags won't be deleted accidentally. But it is not intuitive for the user and it might create tag garbages in the long run? Can anyone explain briefly how OneMore save the tags, how to clean it up(if the Note Container is deleted), or how to print it out (restore it) if the Note Container is deleted accidentally.

A Note Container with a tag
![image](https://github.com/stevencohn/OneMore/assets/8821870/70182681-8e06-4437-8885-f76714f98e14)

**Comment by stevencohn** [comment]
As [mentioned here](https://onemoreaddin.com/commands/Search%20and%20Tag%20Commands.htm), do not modify that text container directly, or as you observed, it will break the relationship.

Tags are stored on the page itself as metadata. This is a standard way of storing OneNote information. That's why deleting the page makes it go away. 

If you want to delete a tag on a page but keep the page, use the same Tag dialog you used to add the tag. This knows how to delete the metadata embedded in the page.

This is similar to the way other OneNote plugins manage on-page information, where the user is advised to use the management UI rather than modifying the content manually.
