### ISSUE TITLE
Make Navigator more customizable, and provide shortcut for adding current page/paragraph to My Reading List.

### ISSUE THREAD

**Issue by jabobian** [stevencohn/OneMore#1072]
# Problem to Solve

Provide a clear and concise description of the problem, e.g. I'm always frustrated when...

The Navigator is great. 
But I found it not quite efficient.  To add a page to the reading list, one needs to clicks multiple times.
Also, it does not provide to paragraph.

# New Feature/Solution

Provide a clear and concise description of what you want to happen.

Basically, I prefer it to show the three groups in tabs to provide more space.
The reading list is basically a bookmark panel. It is preferable to provide Ctrl-Shift-B to bookmark current page.
Additionally, the bookmark panel is preferable to work like a tree outline.
Items can be renamed. With shortcut keys to move up and down, indent and unindent.

The bookmark tree is preferred be saved and activated from another tab or drop down list.

## Alternative Solutions

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Some thoughts:

* Perhaps it's a matter of preference and does, as you say, warrant customizability to show information in panels vs tabs. Many seem to like the in-your-face show-everything panel approach, as was originally requested and implemented, since it's less clicks to get to everything. I'll keep this as a nice-to-have but low priority.
* `Cltr+Shift+B` is interesting because OneMore has both Favorites on the ribbon and My Reading List in the navigator. It could populate the My Reading List. This was intended to be a read-list, temporary parking lot for things to get to, whereas Favorites is I think more what you would call bookmarks.
* A tree view of bookmarks (favorites) is not really necessary because each Favorite and each item in My Reading List indicates its notebook location as a hover tooltip. Your point about activation is solved already by the Favorites dialog (press Alt+F to quickly show favorites and use keyboard navigation to select and activate) Note the Favorites dialog also shows the notebook hierarchy.
* Renaming can be done by renaming the target page directly. That shouldn't be a function of the Navigator. _Although I will point out there is a bug that items in My Reading List are not updated if you do rename a page; the link still works but I'll fix the naming update!_

So I'm down to maybe
1. Ctrl+Shift+B to add a.... Favorite?
2. Fix My Reading List to sync with renamed pages

**Comment by jabobian** [comment]
Hi, Steven, 
Thanks for your detailed comments and explanation. 

Indeed, I think Tree view bookmark is eccential for knowledge management, and it is the key feature missed in Onenote.
Reading list and Favorites are close concept to bookmark but still different.

Though OneNote itself is a tree like document, it is not convenient to reorganize info into new trees, for viewing info from different aspect.
In some tree-like notes apps, there are mechanisms to achieve multiple views. For example, in Leo Editor, one can clone nodes to another tree to reorganize related concepts. In Siyuan-note, notation and Obsidian, when mouse hovers above an internal doc link, a floating window will instantly pop up and display the content of the link. 

I think the biggest strength of Onenote comes from the flexibility of dragging parts all over inside a canvas, which markdown document, pdf documment, office document, and html document cannot provide.

The reading list is just another favorates list. If there are a tree view, we can put them on two branches of the root. 

Making an one-directional reading list is easy even without developing Onenote plugin, for example, by using rest API (Siyuan-note or Obsidian), one can append links in a specified Siyuan document, and one can organize the links as a tree, and such a document can be displayed as a standalone window.  (but still need hardwork to sync with renamed pages). 
I have also developed some standalone tool using Autohotkey, but unfortunately my laptop broken last month.

So, ideally 
1. Ctrl+Shift+B to add a Bookmark, with a link to the Paragraph (not the Page). 
2. renamed pages sync with Reading list and Bookmarks.

The problem comes from saving the bookmark info for each notebook, and when switching to a notebook, the bookmark panel should also switch to its bookmark tree accordingly.

-------

Maybe the Bookmark idea is too complicated and not urgent. You can
1. Ctrl+Shift+B to add current Page to Reading List.
2. renamed pages sync with Reading list.

Maybe later, add
1. Ctrl+Shift+Z to add current Paragragh to a Bookmark List (prefer in a tree view, pertain to a notebook).

Thanks again :)

**Comment by stevencohn** [comment]
Ctrl+Shift+B now bound to add the current page to My Reading List. This will be available in the next release.
