### ISSUE TITLE
Applying format from my styles resets formatting elsewhere

### ISSUE THREAD

**Issue by the-moog** [stevencohn/OneMore#1078]
# Problem to Solve
I used the following recipe for tabulating some 'code' formatted output:
https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-insert-a-tab-character-instead-of-a-table/a180650c-de05-45bb-89db-ec19e0126591 (ref 1)

Though I used \<TAB\> as the metacharacter rather than \t as the latter is likely to appear in script code.

I find subsequent use of the "OneMore->My Styles" toolbar icon to apply styles erases the above format.
The same format applied via the "Styles" toolbar icon does not reset the formatting (but also does not apply the format I need).
Using "copy->format painter" does not reset the format as the OneMore toolbar route does.

# To Reproduce

1.  Use (ref 1) to add a <TAB> metacharacter

2.  Paste some command output, and format it as 'code' using "OneMore->My Styles" 

3.  Use <TAB> to re-format the output of a command, thus.
    ![image](https://github.com/stevencohn/OneMore/assets/3725802/b02c1671-4573-4b3c-b44c-f7daa6eb39bf)
    (ref 2) - sry about image, but I can't paste the formatting here.

4.  Apply the 'code' template using "OneMore->My Styles"  to another paragaph 20+ lines down the page.

Issue:
On step 4, the block in (ref 2) reverted to spaces instead of tabs as in (ref 3)
![image](https://github.com/stevencohn/OneMore/assets/3725802/1b489a38-6aed-4ae0-a32b-d992d18c3d40)
(ref 3)

# Expected Behavior
Subsequent use of  "OneMore->My Styles" should have no affect on previously formatted paragraphs.

# Environment
- Windows 10 Enterprise 22H2 19045.3271
- OneMore Version 5.8.5
- OneNote Microsoft® OneNote® for Microsoft 365 MSO (16.0.14131.20358) 64-bit

**Comment by stevencohn** [comment]
OneNote is not great at always preserving tab characters which is why it doesn't allow them by default and binds the Tab key to convert-to-table instead. The conversion isn't caused by OneMore specifically; instead, this loss in fidelity is caused by the OneNote Interop APIs translating \t to be spaces.

A better approach, one that aligns with the OneNote paradigms, is to use a table with a hidden border. This would result in the same layout as you have above, give or take a few pixels.

You can also use OneMore's Table/Convert Text to Table command, provided you have a clear column delimiter.
