### ISSUE TITLE
Feature: Change tab key to work like a tab key instead of creating a table

### ISSUE THREAD

**Issue by jwhalen99** [stevencohn/OneMore#110]
**Is your feature request related to a problem? Please describe.**
One big complaint many people including myself have with onenote is that the Tab Key does not behave like a tab key but instead it creates a table. It looks like the Microsoft team arent going to fix it.

It would be great if you had a way of overriding this.

**Comment by stevencohn** [comment]
It's a feature! ;-)

The problem is that OneNote is based on a simple mockup language (actually XML with presentation similar to HTML) which doesn't have a built-in concept of columns. So the best I could do is define a secondary keystroke (Shift +Tab maybe?) that would insert 'n' number of spaces. With mono-space fonts, that would help align content but not with all other fonts.

If alignment is the goal, then a viable alternative that you can do now is use a table and hide the borders. Even a single row table with multiple columns is often good enough as long you use the same font size in each column

**Comment by jwhalen99** [comment]
Thanks for the explanation and taking the time to respond. That makes sense. 
Really appreciate your great work.
