### ISSUE TITLE
For the Merge Pages command -insert the titles of the pages as well in the merged document

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#111]
**Describe the bug**
When merging the pages I would like to preserve the page titles as well

**To Reproduce**
Select a couple of pages and merge them. The title of the page should be preserved 

**Expected behavior**
All the pages are merged in the first selected page
I would expect the titles of the merged pages to be preserved, let's say as Heading 1 or Heading 2 or whatever the user whishes to chose (this could be an option)

I know it would be a workaround to copy the title into the test of the page and do the merge after that, but if this is possible it would be great to have that option to keep the page title as heading

Use case: I import web articles via WebClipper; very often they are web pages that are chapters or sections of a book or larger document/tutorial. My workflow includes all the pages in one big document with the title of the document as Heading 1

**Comment by stevencohn** [comment]
There is surprisingly more complexity than you might think. A better approach may be to combine this with #26 which would append all outlines into one Outline. But I have reservations about that one too because the relative position of multiple outlines that are scattered on a page may not be preserved when merging and that may loose context and cause more problems.

So merging page is a cool idea but here are many edge cases that need to be considered.

**Comment by 1001QAdotNET** [comment]
I was very tempted to submit another feature request
As you know I am indenting and collapsing sections 
If I do that and I have a coupe of pages merged the result is a couple of small collapsed outlines scattered over a large page.
I was going to ask to add a feature that would allow the used to see a lost of outlines, order them as needed and then have them relocated , stacked adjacent to each other (that if merging is not possible as requested in the similar feature request)

**Comment by stevencohn** [comment]
Your collapsing dilemma would probably be solved by combining outlines into one. Needs more thought.

Presenting a list of outlines - even prior to merging - has its own problems because it could be really hard to identify which one is which. Remember this would need to work for all users and all cases. Some outlines may only contain images or contain tables. So what do you show to a user so they can confidently identify each outline and know which ones to include? Non trivial and sorry but doesn't seem worth the effort in my opinion.

**Comment by 1001QAdotNET** [comment]
the user could see which outline is which by clicking on a link in the list (the list would include links to them which is possible right?) A name coud le generated by the first sentence in the outline
if it is a picture a small icon (created by scaling down the picture) could be displayed or when clicking on it a pop up could show a smaller size (not icon) of the picture

**Comment by stevencohn** [comment]
Oh is that all? LOL!

**Comment by 1001QAdotNET** [comment]
on paper everything is possible and easy :-))

**Comment by valuex** [comment]
If each selected page is with only one outline, I think it's better to put the merged contents into one outline.

**Comment by stevencohn** [comment]
That's a good compromise - merge containers when all pages each contain exactly one container. Otherwise, containers are collected and added to the target page as originally designed. Releasing soon...

**Comment by 1001QAdotNET** [comment]
This is great I can now work on different pages (to avoid the lag when using the rollover highlighter) and they join the pages. 
Thank you, will test it and I will get back with feedback

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/tag/3.15.1
