### ISSUE TITLE
Shape proportions editable

### ISSUE THREAD

**Issue by LET-Felix** [stevencohn/OneMore#1116]
Hi,

We "need" a feature for OneNote that lets us edit the proportions of triangles and trapezoids (maybe even a custom shape).
Similar to what you can do in Microsoft Word with triangles (video attached). The best-case scenario would be if it were possible to move each point completely freely in space.

[Video of something similar in Word](https://github.com/stevencohn/OneMore/assets/80766635/1671f796-03be-4569-bc2a-a59e6023d5f9)

Is something like that already available in OneNote/OneMore?
Is it even possible?
If yes, how complex would it be to implement something like that?

**Comment by stevencohn** [comment]
Unfortunately, no it's not possible. OneNote's shapes are stored similarly to other Office shape models but OneMore isn't capable of letting the user grab and moving control points or specific edges like this.

**Comment by LET-Felix** [comment]
Thanks for the fast response (:

How complex would it be to implement something like that? 
Does it make a difference when using images instead of shapes?

**Comment by stevencohn** [comment]
It would be virtually impossible to make it responsive and smooth. The only way I can envision it being done is to add a global Windows hook to monitor mouse movements and clicks and attempt to dynamically update the page on every pixel move. Because OneMore relies on OneNote's Interop API, you have to update an entire page (or at least an entire container) and the update function is the most expensive thing you can do. Updates would be extremely sluggish and likely introduce error that would increase exponentially over time as the page shifts under the mouse.
