### ISSUE TITLE
#Hashtag - Tell me your ideas! Give me your opinions!

### ISSUE THREAD

**Issue by stevencohn** [stevencohn/OneMore#1120]
Hi everyone! Steven here. If OneMore had the ability to discover, catalog, and search for #hashtags as explained below, how do you think you would use then? What features would you expect?

The following description is from a [preliminary design document I've posted here](https://onemoreaddin.com/developers/Design%20-%20Hashtags.htm)

> OneNote has a rudimentary tagging system that lets users apply one or more "tags" to a paragraph. Each tag is indicated by a unique icon. Users can customize the name, which shows up as a tooltip over the icon. Users can then list tags within a specified scope. However, the Find Tags function is merely a list of tags within the scope; there is no way to search for a specific tag icon or name. Also, the tag itself doesn't provide any context although the Find Tags feature pulls about the first 50 characters from the related paragraph. Many users have complained about the usefulness of this feature and its implementation.
>
> OneMore Page Tags adds a page-level tagging capability where the user can add one or more tag keywords to a special content box (one:Outline) that appears below the title line, next to the date line. The advantage of this feature is that users can quickly search for one or more tags and navigate through a tree of pages annotated with those tags. The disadvantage is that these page-level tags do not provide a useful context related to the content of the page.
>
> OneMore Hashtags is a new feature that provides a more traditional tagging feature using hashtag-keywords within the text of a page. Typing a hashtag within the flow of content is a more natural and intuitive approach. This also lets users search for hashtags within a page, across pages in a section, or even across notebooks, while also providing textual context for each hashtag. Future enhancements could include the ability to highlight specific hashtags.
>
> _Out of Scope_
> Nested tags such as those in Obsidian which ostensibly emulate a categorization or hierarchy. OneNote already implements this as a structure of notebooks, sections, and section groups. So nested tags would be redundant in OneNote.

And here are some possible user interactions: 

> * Search for tags by name, partial name, type-ahead; AND, OR, and NOT operators
> * Click a tag and show all pages with that tag
> * Click a page - navigate to page
> * From a page, find "related" pages, e.g., other pages that have the same tags (some, all)
> * Build map of related tags - those that are mentioned on the same page
> * Show number of occurrences of each tag; could build a "word cloud"

What do you think? How would you expect to interact with hashtags?

**Comment by netway-pairote** [comment]
* Well, it seems Hashtags feature will make OneMore Page Tag redundant. I am OK with that.
* Typeahead suggestion while typing hashtag on the page content to re-use the previous one.

**Comment by stevencohn** [comment]
@netway-pairote - Thanks for responding!

Redundant? Probably, yes! Page tags are loosely based on OneNoteTaggingKit. I've heard many users not finding page tags entirely useful. This is why I'm exploring a different approach, one that I hope will be more flexible. I expect the end result will be that the best one wins and the weakest one is eventually deprecated.

Typeahead? Unfortunately, no. OneMark dynamically intercepts user input while typing and I've heard from numerous people that it's sluggish and sometimes imperfect. Having thought this type of incept for OneMore, I can understand why it's not a great solution. Microsoft simply does not provide a very good API for that level of interactive behavior.

**Comment by valuex** [comment]
I bet it's going to be a thrilling feature!
A an end user, I'd like to share my opinion on the expected user interface for tagging GUI.
How about using the interface like that of "OneMore Command Palette"?
Tags are actually a small collections of user-defined words, likely in the order of hundreds or thousands.
Tags should be added/indexed fast, so I think the "launcher style window" would be a good choice.

**1. Inputbox**
- Users can type first 2~3 letters to do incremental search of existed tags.
- Also some pre-defined chars can be used to index tags in different scope, like , for this Section, . for this notebook, / for all notebooks. 
- The tagging system could become more smart if it counts the weight of these important factors including recently adding time, frequency, input+excuted.
- With local language indexing support, for example, user can type "nh" for "你好", "Arigato" for "ありがとう". Because the tag list is not going to be very long pratically, so I think this kind of indexing by Roman letter is also high efficient, without switching Input Method and choose the right word.  

**2. Dropdown list**
	Just for user selection to expand the searching scope from this page to this section, this notebook, or all notebooks. For me, I prefer to have the predefined leading char feature, so there is no need for using mouse for selection
**3. Indexed list**
	If user type some keywords, incremental search will be done and the results will be shown in the list simultaneously.
**4. Preview Panel**
	If the user select one indexed tag in the list, he/she can see the paragraphs with this tag.
The results can be clicked to navigated to the corresponding paragraph

![image](https://github.com/stevencohn/OneMore/assets/3627812/fab0f1e8-50f0-48a9-9164-a3437ec1e5ba)

**Comment by seaspeak** [comment]
**Management feature**

I chose not to use the current *Tag page* feauture, because I doubt I could manage them in the long run. In order for me to feel at ease, the tagging system should at least provide *Batch renaming* functionality.

Batch renaming: Users can choose one or multiple tags and give one new name to them. (rename or merge)

**Comment by jasonjac2** [comment]
I have loads of thoughts about tags and logical structures and how different people use them, e.g.. Notebook / Section Groups / Sections / Pages / Headings of different levels.

I have lots of thoughts on showing previews of results (i.e. not just page name)

I think the OneMore page tags are good, but I can't use them due to the page update / author issue.

If you can introduce tags that are actually really just plain text it completely sorts my issue with the OM updating the page and updating the author, BUT it will mean extra functionality to manage typos.  e.g. legal hashtags or ability to see a list of hashtags used in a section or notebook to spot #impotent vs #Important etc.

**Comment by 1001QAdotNET** [comment]
For me tags at page level are ok for now
Indexing is an Windows essential feature and advanced search using indexing is going to be a lot more flexible without adding tags to content unless you want to. 
I used to use dtsearch desktop before Windows Indexing became good enough. It has an advanced yet user friendly search syntax (see here https://support.dtsearch.com/faq/dts0160.htm) 
If we could have something similar in OneNote (on top of what Windows can do) I would say this would be much better (but far more complex to implement) than custom tagging (hash tagging)

**Comment by stevencohn** [comment]
@1001QAdotNET A little tech note... I have an engine that specifically scans for and indexes #hastags (actually, ##hashtags) and uses a Sqlite database for searching and listing, so it's not reliant on the horribly deficient Windows Search.

**Comment by TechNick-92** [comment]
Some thoughts:

I would want to select some text, of any length, right click and be able to apply the hashtag. This should include both typing a new hashtag and select from a dropdown list of existing, saved hashtags. I would want to be able to generate a page summary with certain hashtag, like you can do with One Note Tags currently.  I would want to be able to assign a color to the hashtag, which may or may not apply to the related selected text. In that case, the shade of the hashtag should be darker than that of the text, for ease of visualization. 

While my personal believe is that having 100.000 hashtags/tags does absolutely nothing good, I do think that tags/hashtags can belong to specific subjects or "type of text" when these are not universal (i.e. in the case of tags such as # keywords , # dates, # definitions...).

So, to reduce cognitive load and increase efficiency, I would want those hashtags in the dropdown list to be organized in folders/groups, as an initial, thematic organization. For example, assume you are working on a text pertaining law. You may have these hashtags: case law, evidence, state law, federal law, obiter dicta, ratio decidendi and so on. This would not really be of any use in any other context.

While these could be type in a search box prompted by a contextual menu, having them grouped up I think is useful because you are in control of what you use and it serves as an aid to refrain you from adding unnecessarily many tags. 

Finally, these hashtags could have shortcuts. We could have shortcuts up to the first 10, for example. Then, to make it simple and reuseable without overcomplicating it, you may use the same shortcut commands for different groups, in this way: select a group of hashtag to be the working one for the text/page at hand (or, even section or notebook), and the shortcut commands will select from that group only.  You may make a set of universal hashtags that have set shortcuts, for example, one for keywords, definitions/explanations, dates, insights, names, questions. Then, leave everything else for the user to personalize.

Nick

**Comment by akadormouse** [comment]
From my pov, simple inline #tags are ideal because they transfer with the text and are understood by every program that uses them - whether they be rich text or plaintext. I am very wary of any tagging system that is effectively confined to one program. Similar in that respect to wikilinks. It's one reason I don't use YAML in markdown notes.

I'd like a tags panel to see what I am using already and to provide a filter by tag system. Preferably with ability to define the scope. Otherwise the simpler the better.

**Comment by jasonjac2** [comment]
@stevencohn how are you getting on with this?
Also - on the sqllite DB.  Are you making it broader than just #Tags, e.g. Notebooks / Sections / Pages / Headings?
I ask incremental searching / filter on there things would be great.
Esp if you could add "hover preview".  Clearly another feature, but just checking on your indexing solution.

**Comment by stevenmcohn** [comment]
Hi @jasonjac2. There are certainly use cases that would fit nicely around a Sqlite backing store. For example, you could envision it be the store for the Navigator history rather than a json file, or for Favorites rather than an XML file....

**Comment by stevencohn** [comment]
Hi @jasonjac2. There are certainly use cases that would fit nicely around a Sqlite backing store. For example, you could envision it be the store for the Navigator history rather than a json file, or for Favorites rather than an XML file....

**Comment by 1001QAdotNET** [comment]
> @1001QAdotNET A little tech note... I have an engine that specifically scans for and indexes #hastags (actually, ##hashtags) and uses a Sqlite database for searching and listing, so it's not reliant on the horribly deficient Windows Search.

look for DTSearch (aussie company if my memory serves me well; that engine has a very nice search syntax borderline between regex and regular search engines syntax) that is the best I have ever seen and I have been at this for a long time. 
Just curious, why are you considering Windows Indexing deficient ? (you do need to use some light hacks to make it work with various files but it is fantastic for gathering meta info from the OS; as far as the text searching goes it works for me and this is why I stopped using DTSearch)

**Comment by jasonjac2** [comment]
@1001QAdotNET thanks for the info, I'll take a look. 
I'm not sure if you are asking me or @stevencohn about the failings of Windows Search?
If Me: I haven't used any programming interface against it, but in the interface in ON it is more the syntax and management of results is just too limiting.  I love the interface I have for Outlook and being able to say things like subject: "something" AND to: Jason. Plus I love the way you get the results in a grid.
Compare that to ON where you type in and only really have quotes to help, then you get a list that if you try and pin it, it explodes into something unusable. 

ON: I would love a searchbar with results where I can go:
Notebook: "JAC" AND Title: "[GR:1324]"
and it would produce a list of pages that matched: Notebooks that name contain JAC and page titles that contain [GR:1324]

I use void tools everything for finding files.
I find myself doing monthly ToC's of notebooks and pasting into Excel and then using advanced filters for ON as well as using OM favourites and landing pages with links.

**Comment by stevencohn** [comment]
Jason is correct. Windows Search, at least how it's exposed through OneNote, has a limited operator language. You cannot quote spaces within strings, for example "Big Dog" will not search only for that two-word phrase but instead search for "Big" and for "Dog" separately. It's also impossible to search for "#hashtag" as it will ignore the pound sign and show all instances of "hashtag". It falls down in other ways too.

DTSearch looks cool but it's a paid license model which doesn't fit with OneMore's open promise.

**Comment by jasonjac2** [comment]
@stevencohn  are you writing it from scratch or basing it on another repo?

**Comment by stevencohn** [comment]
Currently, this is just about #hashtags so writing it from scratch is the best approach. There are no other repos that I know of that provide text search capabilities that can dissect the OneMore XML schema.

**Comment by 1001QAdotNET** [comment]
Using OneNote for searching means opting for light searching 
Windows Indexing can and it will index OneNote files if configured
Then the advanced search syntax could be used https://learn.microsoft.com/en-us/windows/win32/lwef/-search-2x-wds-aqsreference

**Comment by stevencohn** [comment]
I understand what you're saying but you're missing the point of this conversation. Let's keep it to end user requirements, not implementation.

**Comment by akadormouse** [comment]
Personally I see #tags as a simple filter and document management system, that is quite distinct from content search. Might or might not use the same indices or search technology. Most programs that use them also have detailed search.

**Comment by PaulJamesTaylor** [comment]
I use both Onenote and Obsidian so find this proposal interesting as it would close one of the gaps I have observed between these two products.  I really don't like Markdown editors and find Obsidian very aggravating at times when creating complex notes, and its unusable for collaboration with my team, but its UI is fantastic and its tagging feature, similar to what is proposed here, is very useful and convenient.  For strictly hierarchical organization Onenote is vastly superior to Obsidian, where you rely on a folder hierarchy, but nested tagging does somewhat make up for that deficiency and in Obsidian it is super easy to apply tags so its one feature I would say Onenote could benefit from.  Not sure why the core dev team hasn't done this obvious work, so appreciate the thought Steve has put into it.

In Onenote I use both paragraph level tags as well as page level tags offered by Onemore, but I find the former of limited value  and am not consistent with the latter as it is somewhat cumbersome to apply them.  Writing the hashtag at the top of the note, as is done in Obsidian, is very efficient.  

This is a tangential issue, but does relate to the efficiency of using Onemore tagging.  I have had the application crash on me when applying tags - I would guess about 1 every 20 times.  Normally I can quickly reboot the app, but this happened once during a meeting I was conducting over video and I wasn't able to reboot the app and couldn't get it working until I rebooted my workstation.  I haven't been able to come up with a replication pass so have not reported it yet, but to be honest its been an impediment to adopting it more consistently.  But there are some pages that I will definitely take the time to tag.

**Comment by Rishabhsahu325** [comment]
1)I feel tags can be useful when users require visiting pages or paragraphs that relate to topics mentioned by those hashtags. So for example if I had a notebook related to exam preparation ,and I am storing problems arranged in pages that are ordered chapterwise. Then I will find the hashtag feature useful if a particular concept is used in solving some questions from different chapters , but the concept can't be dedicated a separate chapter , since it will require redundant pages.
2)Users can also use it to filter notes which they want to mark with a certain topic ,but using the search feature does not help since the keywords that describe that topic are also present in other notes. Like I want to search all notes that I tagged as important. Now usage of the word "important " instead of a tag in search bar might show up notes that are not tagged important/ are not important for the user but just happen to contain the word "important" in certain paragraphs do describe something.
3)Another thing is that there should be less limitations to the number  of hashtags a user creates .According to the scenarios I discussed ,it will be very limiting if while studying I am only able to create tags for 5 topics ,whereas exams might have more than 50 topics or concepts.

**Comment by maslos** [comment]
Hello, can i ask for a feature to preserve original image/attatchment filenames when exporting? 
When i do "save as" i can save photo/attachment with original filename but when i export with OneMore it renames all photos to something like "Photo01".

**Comment by PaulJamesTaylor** [comment]
@maslos you should add that request here:  https://github.com/stevencohn/OneMore/issues
