### ISSUE TITLE
Create Heading takes a long time

### ISSUE THREAD

**Issue by F-Passion** [stevencohn/OneMore#1137]
Create Heading takes a long time

Thanks to the developers for letting OneNote generate toc.

I encountered the problem of creating Heading that took a long time. In the body of my notes, I needed to create all levels of Heading using onemore. Each operation took 3-4 seconds, which made me feel uncomfortable. Several attempts to uninstall and reinstall the plug-in and delete the configuration file have not been resolved.
Here is the log information:

To Reproduce

1. open onenote
2. applying style Heading in the notes
3. wait 3-4 seconds
4. See the heading style

log file

01| Starting dllhost 16308, 2200 Mhz, 16 MB, zh-CN/zh-CN, v5.9.0, OneNote 15.0, Office 16.0, 2023-10-11 09:05
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16827.20130)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
03| ..building ribbon
03| ..building ribbon colorizer commands
03| ..building ribbon language proofing commands
03| ..building context menu
03| ..OnStartupComplete(custom[])
03| ..starting command service
03| ..starting reminder service
03| ..starting navigation service
03| ..ready
04| defined 45 hotkeys for input locale 2052
06| Invoking command InsertTocCommand
04| Running command ApplyStyleCommand
04| ..loaded page; applying style Heading 2 @ 00:00.50
04| ..applied style; saving page @ 00:00.51
04| ..saved page @ 00:03.60
06| OnBeginShutdown(custom[])
06| ..shutting down UI
06| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
06| ..disposing 5 streams
06| ..closing log

**Comment by F-Passion** [comment]
Even worse, it seems that every action has delayed. For example, after clicking on the heading in the navigator, you must wait 2-3 seconds to jump to that location
这种感觉太难受了吧

**Comment by jasonjac2** [comment]
When you say "navigator" do you mean the navigator dialogue OR clicking the ToC that has been put on the page?
I have a hunch (only a hunch) that the navigator starts to drag the system a bit, but haven't done much / any research.

I find the ToC tool execution time depends on the size of the page.  I think it would be good if there were a debug flag where you could set to get OneMore to log the stages:
- invoke & UI up; Get Page; Parse page; save page.  I am not sure updating the page is async or sync, but it feels like it is Sync as the UI hangs till the page is updated.

**Comment by stevencohn** [comment]
This comes down to page size. I've done extensive testing. The Microsoft OneNote Interop API used by OneMore is very quick to load even large pages. But the larger the page, the slower the API is to save the page back to OneNote. And it is a synchronous API. There's really nothing OneMore can do about this unless/until Microsoft improves the API.

I have a task underway to limit the save operation to only _outlines_ on the page that have changed, but I suspect that the vast majority of users have a single outline on most pages so this still won't solve those cases or cases where the affected outline is still quite large.

It is possible to warn users that "the current page is large and OneMore operations will be slow" but I think that may more annoying than anything.

Otherwise, there's not much I can do I'm afraid. I have to mark this as Won't Fix.

**Comment by jasonjac2** [comment]
"I have a task underway to limit the save operation to only outlines on the page that have changed, but I suspect that the vast majority of users have a single outline on most pages so this still won't solve those cases or cases where the affected outline is still quite large."
Yes, 99.5% of our 6K+pages are single outline.
I've just had a penny drop moment. 
I know you have told me this before.

**Comment by F-Passion** [comment]
> "I have a task underway to limit the save operation to only outlines on the page that have changed, but I suspect that the vast majority of users have a single outline on most pages so this still won't solve those cases or cases where the affected outline is still quite large." Yes, 99.5% of our 6K+pages are single outline. I've just had a penny drop moment. I know you have told me this before.

I found a way:
1. use CTRL + Alt + 1，create heading in the text, not use onemore's ctrl+alt+shift+1
2. define onemore's style , set heading1, heading2, normal...
3. finally, apply style in this page, just wait 2-3 seconds, the onenote's style ---> onemore's style
4. 
My English is poor. I hope I have made myself clear~

**Comment by F-Passion** [comment]
There's another problem：the operation of insert a Text Box also cost 3-4 second ，

the log file is：
19| Running command InsertBoxCommand
19| SaveToMRU skipping InsertBoxCmd, method not found

**Comment by jasonjac2** [comment]
One possible work around for this @stevencohn is my idea ages back of having commands deliver their output to the clipboard rather than to the actual page.  I was just looking for the number, but can't find it.   
In its richest form it was to have an option to intercept when you create content and add to the page and instead just copy it to the clipboard.  The user could then paste it where they want it and ON's UI doesn't suffer the same hang.

So instead of colourising the selected or adding a ToC to the top of the page, it would just save it to the clipboard.

**Comment by stevencohn** [comment]
@jasonjac2 I understand what you're saying. And that may work for some cases. But it feels overly clunky, especially for most users looking to quicken their workflows. And yes, I certainly realize the irony of that statement. But I'm also afraid of other known (to you and me!) problems with a shared clipboard, timing, observability, etc. I won't rule it out 100% but I'm considering a last option.
