### ISSUE TITLE
Double-click favorite to jump to page

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#1157]
# Problem to Solve

There are two obvious ways to use favorites: the keyboard and the mouse.
1. Mouse
Click on Favorites and select an item from the list. This works.
1. Keyboard
 `<alt>f` open dialog, start typing and hit enter when desired favorite is highlighted. This well. 
(Note: I still do not understand why it does not just show the same menu as the previous option. Showing links just clutters the interface and they cannot be changed in the search dialog.)

**What is missing is the hybrid use. If the user opens the search dialog and sees the favorite they want, they should be able to just double click on the name to go to the page.**
(Actually, a single click should go to the favorite because selecting it has no other purpose.)

# To Reproduce

1. `<alt>f` to open favorites
2. double click on a name

# Expected Behavior

I would expect to go to that page

# Screenshots

# Environment (if applicable)

 - OneNote Version: O365, 64bit?]
 - OneMore Version 5.9.0

# Additional Context

I have created a separate feature request #1156 with the way that I would like to see favorites to work. If go to favorite was implemented that way then this issue is N/A.

**Comment by jasonjac2** [comment]
@julie777 totally agree on the double click. 
Single click IMO should select, because I think you should be able to do other things with the row, e.g. "copy link to page", be able to overwrite the name to make more sense in the context of your favourites. (column for page title, column for custom title and favourites shows custom title if you have entered one).

I would add Ctrl+# to select the row
up down to always navigate in the grid 
typing always filters
Button to "add current page", then I wouldn't need the ribbon at all
Order by "the order", "most frequently selected from filter dialogue box"

**Comment by stevencohn** [comment]
Double-click added
Add Current Page button added
