### ISSUE TITLE
ToC Formatting

### ISSUE THREAD

**Issue by GaryB-B** [stevencohn/OneMore#1208]
# Problem to Solve

As a company utilizing shared OneNote notebooks for our knowledge base, we prioritize consistency in formatting across our documents. We regularly use OneNote's default style for uniformity, as our notebooks have multiple editors. While the Table of Contents (ToC) feature in OneMore is functionally excellent, we've noticed that the heading used in the ToC does not match the standard 'Heading 1' style of OneNote, which means the ToC looks a little different from the rest of the sheet.

# New Feature/Solution

Could you consider updating the ToC feature in OneMore so that it automatically adopts OneNote's default 'Heading 1' style? Otherwise, allow it to adopt a custom style. It's a small detail but helps to achieve the consistency that we need.

## Alternative Solutions

It is of course possible to manually change the formatting of the ToC header, but whenever the ToC is refreshed it reverts to the preset style.

# Additional Context

Example of Knowledge Base page within shared OneNote notebook:
![image](https://github.com/stevencohn/OneMore/assets/153469584/b5091836-2a4d-4ed5-a448-79739b7c524b)

**Comment by jasonjac2** [comment]
OT: @GaryB-B is your Co an IT co.  We use ON for support / KB and I really want to find other co's that use it the same to derive some best practices.  I started #1130 for this.
@stevencohn whilst you are on this one, the placement of the ToC can be a bit of an issue as well.  Our pages ALWAYS start with 3 or 4 lines, that include an overview of the page.  That way you don't have to page down past the ToC.  So if the ToC command could locate the existing ToC and replace it, rather than always put at the top, that woudl be great.

**Comment by GaryB-B** [comment]
Thanks @stevenmcohn, that fix is perfect!
