### ISSUE TITLE
Clarification on Calendar criteria

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1259]
# How can I help you?

Ask away...
https://onemoreaddin.com/the-basics/OneMore%20Calendar.htm
Hi - I was looking at this and the Onetastic one.  I am trying to establish the exact criteria and hoping you would update the docs accordingly.
1) Are these pages just modified / created.
1.1) how likely is visiting a page likely to create an "edit" - e.g. if you move the edit caret is that an edit?
2) Is this just for my changes or by all users?
3) If I modify an page on multiple days, does it appear on all days that it was modified or just the last date?
4) Is it possible to see the difference between create and edit?
5) Is it possible to see who edited it on that date?
6) Suggestion: Link the cal and the Nav history part of the docs as users may benefit from the other and may not know they exist.

Aside: OneTastic has just included a Time of Day to show whether it was AM / PM etc.

Aside Aside: I was going to look at harvesting Navigation.JSON changes to keep a forever log of where I have been.

Thanks for the clarifications in advance and hopefully they can make it onto the Cal / Nav docs, so I don't end up asking again next time I have a "how does this work".

Thanks as always.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Will update the wiki. For now, some quick responses

1. It does appear that OneNote updates the page level lastModifiedTime when you move the text cursor insertion point. However, it does not appear that the paragraph-level lastModifiedTime stamps are touched. So this does confuse Calendar and makes it much more difficults (non-performant) for Calendar to detect _real_ changes.
2. Would be for all users since Calendar looks at the page level lastModifiedTime value.
3. Just the last modified time is known. Calendar is not a tracker, just a current known status report
4. Might be bug in Calendar. You can enable Created/Updated in settings. It's supposed to show all pages created on a specific date or udpated on a specific day, which means a page could appear on two different dates. But I think the Created option is broke?!
5. Author - I could add that to the right-click thumbnail

AM/PM - if you hover over a page link, it shows the timestamps in the bottom status bar. So I beat Onetastic ages ago! ;-)

Thanks for the Qs

**Comment by stevencohn** [comment]
There was a little bug in the way it was filtering modfiied/created pages per day. If both modified and created options were enabled, it only showed when a page was modified. Now it should show each page on the day it was created and the most recent day it was modified if both settings are enabled.
