### ISSUE TITLE
Version 6.1 slows down OneNote extremely

### ISSUE THREAD

**Issue by kurtsoeser** [stevencohn/OneMore#1264]
Hi Steven!

Thanks again for your Addin, but I (and some other users) are experiencing a very slow OneNote with the new version

Going back to 5.9 and there are no problems with speed...

Do you have an idea what could possible cause this?

**Comment by stevenmcohn** [comment]
If you have large notebooks with many pages, the new Hashtag feature will build a catalog the first time. Others have seen this take upwards of 90 minutes for 6000 pages.

This is a duplicate question to https://github.com/stevencohn/OneMore/issues/1226

**Comment by stevencohn** [comment]
If you have large notebooks with many pages, the new Hashtag feature will build a catalog the first time. Others have seen this take upwards of 90 minutes for 6000 pages.

This is a duplicate question to https://github.com/stevencohn/OneMore/issues/1226

**Comment by jasonjac2** [comment]
I love my "Chaos of Notes" is a benchmark :-).

**Comment by stevencohn** [comment]
@Test-Acount sorry you feel that way, you can disable the hashtag feature in the settings. The only services used by OneMore are [disclosed here](https://onemoreaddin.com/get-started/Online%20Services.htm). Minimal data is transported to these services, primarily the Pronounce command and the PlantUML command.

The next version about to be released does attempt to address the performance issue.

The next+1 version will attempt to completely decouple the scanning service to a separate Windows service to eliminate any performance problems altogether.

**Comment by jasonjac2** [comment]
@Test-Acount just to be clear - it is scanning your notes and storing some information about your notes on your PC only.  I can't see how an add-in can do all the things the add-in does without scanning your notes (it has extensive search / find all text that is the same as this page name etc etc).

@stevencohn didn't intend for the new feature (hashtags) to cause a burden at install and in fact it is the most likely cause, but there may be others.  When I noticed it and did some testing, I my PC locked with ON running overnight.

I would recommend sticking with it, but that is only because I know how much this add-on has helped me and so I am willing to invest my time (in a tiny fraction of the way Steve has) to make the product better give feedback and help track issues down.

Aside: if you have left the the system idling for a long time and it is still a problem, then it may be something else and woudl need investigating.

**Comment by jasonjac2** [comment]
@Test-Acount Looking at #1268 log you attached, it looks like the hashtag service had completed scanning your pages and so I don't think it was that slowing your system down.  Were you keeping the OneMore navigator / OneMore Favorites / other OneMore screens up for a long time?

**Comment by stevencohn** [comment]
@jasonjac2 The hashtag db creation step completed but the scan did not complete. Otherwise, you would have seen something like this:

`hashtag service scanned 1474 pages, updating 0, in 47614ms`
