### ISSUE TITLE
OneMore doesn't Seem to function.

### ISSUE THREAD

**Issue by rlolingo** [stevencohn/OneMore#128]
Hi and thanks for building this wonderful plug-in, I use onenote often and I think i'd very much welcome this plug-in.
Unfortunately, it just doesnt seem to function lol.

I see that the slow/sluggish Ribbon Selection is a common issue and im experiencing that.
Though, despite the waiting times, the functions simply don't perform.

E.G: I'd Click "Favourites" -> "Add Current Page" but nothing at all happens.
Same for any of the functions i've tested. I've still to test a few more, but is a bit longsome because of the waiting time.

Besides that, it might have bugged out OneNote in general: 
![image](https://user-images.githubusercontent.com/34475976/102477172-ea29c000-4053-11eb-8ce6-9d495eb5daa1.png)
![image](https://user-images.githubusercontent.com/34475976/102477225-fc0b6300-4053-11eb-8407-30a730ca791e.png)

I've tried both 32 and 64 bit installers, but not much seems to improve. 
Heres the Version of OneNote im using:
![image](https://user-images.githubusercontent.com/34475976/102479041-4857a280-4056-11eb-96f7-88e56806e959.png)

---
I don't remember pressing submit, sorry for that first post.
to respond: yes i am a new user, using OneMore v3.10.6

**Comment by stevencohn** [comment]
Would you possibly be able to attach the log file? You can find it here:

%TEMP%\OneMore.log

same as C:\Users\your-username\AppData\Local\Temp\OneMore.log

**Comment by rlolingo** [comment]
Indeed, here you go.
[OneMore.log](https://github.com/stevencohn/OneMore/files/5708883/OneMore.log)

**Comment by stevencohn** [comment]
I did some digging and quite honestly, it does sound like your OneNote installation is a bit hosed.

The fact that the log file is created at all means that the add-in is starting which is good. But it doesn't finish starting which is bad. It fails at the very first interop with OneNote which tells me that OneNote's COM interface is not working properly. Immediately after that failure, the add-in shuts itself down which is why no commands are functioning.

As for the slow ribbon, I presume you're talking about the OneMore ribbon menu only? The rest of the ribbon works fine? I'm pretty sure I've addressed all known issues with ribbon performance but it will be slightly slower when viewing a very long page because it loads the current page to get context information. Having said that, since the add-in COM Interop isn't working, I suspect it's just OneNote misbehaving due to the failed startup.

So I've never see this before and can only advise that you attempt to install Windows updates if you're not already up to date. And maybe try to repair-install OneNote. I'm sorry I can't be of more help. Sometimes these things are really difficult to diagnose remotely.

**Comment by rlolingo** [comment]
I see, I had a feeling there was something up my end. 
No problem, and thanks for your time regardless.
I'll try out some things and see if i can get some results.

**Comment by rlolingo** [comment]
So I updated the software, and nothing changed.
But it turns out I just needed to repair it, via Windows Apps & Features.
Still exploring features, but things are working now. Thanks 👍

**Comment by stevencohn** [comment]
Nice. If you have any other questions, requests, complaints, big monetary donations.... please feel free to reach out!
