### ISSUE TITLE
Feature request - One My style Type contains 3

### ISSUE THREAD

**Issue by Test-Acount** [stevencohn/OneMore#1281]
# Problem to Solve
# New Feature/Solution
One My style Type contains character, paragraph, Heading, because I want to use the same style for all three, so I can use one style instead of three.

get some feature request, post 3 most wants.
I can almost give up the onetasic, onemore does all my needs, really appreciated.

**Comment by stevencohn** [comment]
Not sure I fully understand this one. Could you please elaborate how you think this would work?

**Comment by Test-Acount** [comment]
currently one style just can act on one part ( character, paragraph or Heading).
I want one style can act on character, paragraph and Heading at the same time.

**Comment by stevencohn** [comment]
OK so I think you mean a character style that only applies the highlighted attributes in this picture. It would _not_ change font family, size, spacing, or advanced options.

<img width="348" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/ca4e2f99-5e8d-4ede-9230-6390e428c268">

**Comment by Test-Acount** [comment]
![Screenshot 2024-01-23 111943](https://github.com/stevencohn/OneMore/assets/13340945/4e0ddee9-7887-4955-b5e0-bbf37e58eb78)
it's the style type, u can just select one, i want select 3.

**Comment by stevencohn** [comment]
Unless I'm misunderstanding something important, I don't see any difference between the proposal and the Character style.

In order for it to work, this new "Global" style would have to be excluded from the _Apply Styles to Page_ command, otherwise it would interfere or override the char/para/heading styles. So you would only be able to apply it manually on-demand, and that is no different than a Character style. 

When you apply a Heading style, it changes the text to a heading. This is different than other normal text because headings are used to create tables of content. So a single Global style wouldn't know what to do!
