### ISSUE TITLE
add an option to only display Current Page Headings

### ISSUE THREAD

**Issue by liuyuqiangchn** [stevencohn/OneMore#1331]
Hello, I like The Navigator window very much. However, I mainly use Current Page Headings and not My Reading List and History. I would like to ask if you can add an option to only display Current Page Headings. Thank you.

**Comment by jasonjac2** [comment]
I pushed hard for the 3 bits - Reading pane / History / Current Page.   You can resize those other panes.   I would love to have a checkbox on the "Current Page" so that the place where the edit caret is is always highlighted in the "current page" and visible.
I agree with being able to turn them off if you don't want them - they must take up clock cycles to keep them updated (the history one). I have also asked for them to be tabs rather thank adjacent listboxes to better use the space.
