### ISSUE TITLE
希望添加单元格合并/取消合并功能

### ISSUE THREAD

**Issue by styuanqn2022** [stevencohn/OneMore#1342]
# Problem to Solve

Provide a clear and concise description of the problem, e.g. I'm always frustrated when...

# New Feature/Solution

Provide a clear and concise description of what you want to happen.

## Alternative Solutions

Provide a clear and concise description of any alternative solutions or features you've considered.

# Additional Context

Provide any other context or screenshots about the feature request here.

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by BH2WFR** [comment]
cell merging/unmerging feature is just updated on newest Office 365 Onenote. YET office 2024 onenote didn't updated this button on the ribbon bar, but can normally view table with merged cells.
最新的 Office 365 Onenote 刚刚更新了单元格合并功能，但是好像是 365 专属，普通版本的 Office Onenote 没有看到这个按钮，但仍然可以打开合并单元格的表格。

Though I'm a 365 user, It seems that cell merging feature is technically able for the addons to implement, for office 2024/2021/2019/2016 users to be able to try this new 365-only feature.
尽管我是 365 用户，但插件理论上似乎是可以给 office 2024/2021/2019/2016 用户实现这个刚刚给 365 更新的功能的。
@stevencohn

**Comment by stevencohn** [comment]
Wow! I just checked my installation on my work computer and, huh, I'm very surprised! I'm on O365 release version, so it's not just beta. I also use OneNote 2024 on my own personal computer and can verify that the button is not included in that version.

> Microsoft® OneNote® for Microsoft 365 MSO (Version 2509 Build 16.0.19231.20138) 32-bit 

Thank you for pointing this out. This will make many, many users very happy.

While I can't add this specific button on the ribbon in older versions of OneNote, I can investigate what O365 is doing to the table definition behind the scenes. Maybe I can replicate that.

**Comment by stevencohn** [comment]
Oh no. Sadly, it looks like this is implemented in the binary storage model of the page, but it has not been exposed through the interop API into the XML schema. Without information in the XML schema, OneMore cannot control cell merging.

Even worse, if you use OneMore to modify the page in any way, cell merging will be lost! Since the merged cells are not specified in the XML, when OneMore saves the page, that information is overwritten in the binary storage model.

Unless Microsoft exposes this through the API and into the XML Schema, there's nothing I can do about that. I can't even detect that case and warn you.
