### ISSUE TITLE
I can't add a caption

### ISSUE THREAD

**Issue by ankiman1** [stevencohn/OneMore#1352]
# Problem to Solve

when i try to add a image caption the image erases. 

# To Reproduce

1. click image
2. add caption
3. image erases

# Expected Behavior

1. the command add a caption

**Comment by stevencohn** [comment]
There are rare cases where the addin (or another addin) crashes and it's dllhost.exe process remain even though you close OneNote. When you reopen OneNote, the addin will not load again because it's conflicting with the running dllhost.exe process. I would need to see your OneMore.log file (located in the %temp% folder)

For the Image Caption failing, I'd need to see your page to understand why it's losing the image. I've never seen that before. Can you export your page as a .one or .xml file and attach it here?

**Comment by ankiman1** [comment]
[failing caption and OneMore.log file.zip](https://github.com/stevencohn/OneMore/files/15052094/failing.caption.and.OneMore.log.file.zip)

**Comment by stevencohn** [comment]
The caption is failing because that is a background image, which I will fix. If you make it a foreground image - inline with text content - then the caption will work properly.

I'll look into the log file as well; there appears to be a few exceptions in there....

Thanks for the zip
