### ISSUE TITLE
I hope OneMore can have this function to allow the pictures on the web page to be pasted into OneNote!

### ISSUE THREAD

**Issue by mengxin523** [stevencohn/OneMore#1358]
I often need to copy the content and pictures on the web page to OneNote, but in most cases, the text can be pasted normally, but the pictures can not be done, it should be the format of the web picture, OneNote can not recognize the image format, I hope OneMore can have this function to allow the text and pictures on the web page to be pasted into OneNote!

Thank you so much!

**Comment by stevencohn** [comment]
Can you provide an example Web page that demonstrates the problem?

**Comment by stevencohn** [comment]
There's some scripting on the page that's restricting copy/paste of content if you're not logged in. I do not have an account so it's blocking me from doing that. I tested these scenarios:

* Print page to OneNote - OK, but results in static full-page images, not text+pictures
* OneMore/File/Import Web Page as static content - OK, but same as above
* Right-click on a single image and Copy, paste into OneNote - OK
* Select content  including one or more pictures and Ctrl+C... BLOCKED
and
* OneMore/File/Import Web Page - BAD, I think because the page is very complex, the scraping logic is getting confused

So the workaround, although not perfect, is to copy each image individually. At least on this page, they appear to be PNG files which should be saved in OneNote without a problem.

**Comment by mengxin523** [comment]
Maybe you can try this Web :
https://zhuanlan.zhihu.com/p/576560999
If you are asked to log in, just turn off the login box

**Comment by mengxin523** [comment]
![Uploading ShareX-2024-04-29 08-49-54 2314.png…]()

**Comment by jasonjac2** [comment]
Have you tried using the OneNote clipping add-in.
You don't say what  browser you are using.

**Comment by stevencohn** [comment]
It appears to be the same problem on this page too. I can click on a single image to expand it view, then right-click and choose Copy, and it will paste fine into OneNote. It's only when you select text and one or more images that the paste operation doesn't work. Again, I think there's some JavaScript on the page that's limiting the copy.

**Comment by mengxin523** [comment]
I can't copy and paste the image here, even if it's a single image , I don't know what's going on...

**Comment by stevencohn** [comment]
Closing this as there doesn't appear to be anything to do. There is a protection mechanism on those web site preventing the copying of images.
