### ISSUE TITLE
There is a way to paste an image in the same line of a text?

### ISSUE THREAD

**Issue by ankiman1** [stevencohn/OneMore#1362]
# How can I help you?

there is a way to do this in one note? Can i paste an image in the same line of a text, and then, when i move the line the image follow the same behaviour of the text? 
<img width="683" alt="image" src="https://github.com/stevencohn/OneMore/assets/166498817/c568b056-a96d-4060-ab3f-b7dc9567f337">

**Comment by stevencohn** [comment]
Sadly, no. This is not a capability of OneNote so cannot be done by an add-in like OneMore.

**Comment by stevencohn** [comment]
In your example, one possible workaround is to explore the Segoe UI Emoji character set, or similar char sets. Since they are just fancy text characters, they will flow with the text.

<img width="313" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/be9aca7e-e61a-4083-a7a6-0d7a0343cce4">

**Comment by ankiman1** [comment]
ok. so is it impossibile to paste whatever image in the same line ?

**Comment by ankiman1** [comment]
thanks :)

**Comment by jasonjac2** [comment]
windows key + fullstop and select from the emoji's book is what I use 📑when I am in OneNote.  I find it useful when I am saying things like:  now tick the checkbox that looks like ⬜

**Comment by ankiman1** [comment]
> windows key + fullstop and select from the emoji's book is what I use 📑when I am in OneNote. I find it useful when I am saying things like: now tick the checkbox that looks like ⬜

thanks :)
