### ISSUE TITLE
 “Spilt pages” wont spilt the title wit"《》” symbol.

### ISSUE THREAD

**Issue by mmschzs** [stevencohn/OneMore#1379]
# Problem to Solve

fitst:
![image](https://github.com/stevencohn/OneMore/assets/67103160/0ab57b16-0039-4dec-b0a2-cf0c5cf7910e)
then:
![image](https://github.com/stevencohn/OneMore/assets/67103160/2d741479-69fa-4ae3-9653-0d109e96eda4)
“无标题页”means there are no title.

# To Reproduce

# Expected Behavior

# Screenshots

# Environment (if applicable)

 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Working on a fix. Although it doesn't have anything to do with the《》characters; instead, it's because there is no content beneath each heading. It should work either way, so I'll fix that.

Meanwhile, there is a workaround you can try. If you format those headings as a bullet list, then you can use the OneMore/Page/_Create Pages from List_ command. That will work with just the headings as content:

<img width="403" alt="image" src="https://github.com/stevencohn/OneMore/assets/9964757/ef01d402-05f8-471e-850e-7c4f37398aff">
