### ISSUE TITLE
Allow Custom Styles and Snippets or any other OneMore command to be added to the context menu as a whole or individual subcommands as for the other options already allowed in the context

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#143]
**Is your feature request related to a problem? Please describe.**
Allow the Custom Styles and Snippets to be added to the custom menu

**Describe the solution you'd like**
As a matter of fact the user should be allowed to add command or group of commands he or she wishes to the context Menu

**Describe alternatives you've considered**
N/A

**Comment by stevencohn** [comment]
The Favorites menu is dynamically generated. OneNote knows this and when you right-click on it or any of its items, its only gives you the option to "Add Menu to Quick Access Toolbar". OneNote doesn't allow individual items from a dynamic menu to be added because they could be removed at any time and there is no way for OneNote to confirm that the command behind the item still exists.

The reason the Favorites menu is dynamic is to allow ad-hoc addition and removal of favorites, plugins, and snippets to instantly be reflected in the menu without having to restart OneNote. That is much more import than being able to add individual commands to the Quick Access toolbar in my opinion.

**Comment by 1001QAdotNET** [comment]
this was about the context menu (the one that shows up when you right click on text) not about the quick access menu

**Comment by stevencohn** [comment]
Ah. Coffee.  But I don't think it's worth it... either right click + click = 2 clicks, or click favorites + hover to pop-out menu and click = 2 clicks. And honestly, how many commands do you have on the context menu now? It must scroll off the screen! :-o

Anyway, I still maintain that plugins are an experiment. And that you're the only one in the world using them. And there are other features I want to focus on. So sorry.

But I am contemplating rewriting the way the context menu works so maybe I'll include consider in the future but no promises.

**Comment by 1001QAdotNET** [comment]
Fair points.
How about allowing the user to assign shortcuts to saved plugins?
