### ISSUE TITLE
Duplicate feature uses today's date not original page's date

### ISSUE THREAD

**Issue by bombledmonk** [stevencohn/OneMore#1450]
# Problem to Solve

If I duplicate a page using the context menu, the resulting page's date is today's date.  If I manually copy/paste a page new page the same date as the original page.  

# To Reproduce
Duplicate any page with a date older than today.

# Expected Behavior
I guess I'd expect the page's date to be the same if it's a "duplicate".   

# Screenshots
Original
![image](https://github.com/stevencohn/OneMore/assets/4141691/d1a68a32-6203-43a5-b96f-e527b7d5984e)
![image](https://github.com/stevencohn/OneMore/assets/4141691/60f1a5e0-7287-4737-8c3f-c40d86d82e84)
![image](https://github.com/stevencohn/OneMore/assets/4141691/300b5cc4-acf8-46d2-be97-e6ce2d668699)

# Environment (if applicable)

 - OneNote Version: OneNote 16.0.16731.20716
 - OneMore Version Version 6.4.0 

# Additional Context

Totally understand if this doesn't get picked up, and it might be just one person's idea of expected behavior, but this did seem counterintuitive to what I thought would happen.

**Comment by stevencohn** [comment]
I'm not sure I, or others, would agree. The original intent is simple - to create the copy immediately after the original and tack on a numeric counter to ensure the page title is unique. Since the title is different, that makes it a "new" page. If it were the same as Copy/Paste, there would be no reason to create this command.

This might be an 80/20 situation where the command makes 80% of users happy and the rest have to do more work.

The workarounds are simple. You could just stick to copy/paste if that's what you need, or you can update the date on the new page by clicking on it and choosing a new date.

**Comment by bombledmonk** [comment]
Understandable given the difficulties of semantics of a word like Duplicate.   At least this is sitting here if other people come in with similar differing opinions. I had first looked through the settings to see if that behavior was configurable, but didn't notice anything so my next stop was here.       

Thanks for making an excellent tool in your free time and for the quick response.

**Comment by jasonjac2** [comment]
I'm with Steven - I would expect it to be a "new page" and have the current Date / Time as more useful than original.  I also get @bombledmonk logic for wanting a carbon-copy, but my use cases I would be wanting to have the current date and time.
