### ISSUE TITLE
Increase/Decrease Font size affects all display containers on a page

### ISSUE THREAD

**Issue by s0j0urn** [stevencohn/OneMore#1478]
Hello

Thank you for creating this wonderful piece for software for Onenote users.

Regarding my query, I wasn't sure if it is a bug or a request for enhancement. Therefore, I am raising it as a question.

When I gtry to increase or decrease font size it affects the font size of all the text containers on the page. Is it possible to increase/ decrease font size of only the selected container or selected text on a page?

**Comment by stevencohn** [comment]
I think there may be a bug.

To be clear, you're using the OneMore Edit commands, _Increase/Decrease Font Size_, correct? Compare this to the built-in native OneNote increase/decrease actions accessed via `Ctrl+Shift+<` and `Ctrl+Shift+>`.

As mentioned on the [OneMore Wiki](https://onemoreaddin.com/commands/Edit%20Commands.htm), the OneMore variants will 

> "[change] the font size of _all text on the entire page_. To increase the font size of selected text, use the built-in OneNote
> shortcut Ctrl+Shift+>"

Having said that, I think I did in fact find a bug while ensuring my memory was correct! :-) Thanks for helping me find it.

**Comment by s0j0urn** [comment]
Yes, I was using OneMore Edit commands. Thank you for sharing the OneNote shortcuts.

**Comment by stevencohn** [comment]
The OneMore increase/decrease command have been fixed to properly adjust font sizes across all containers on a page. That is its intent and what makes it unique to the built-in OneNote commands. The built-in commands are (only) slightly harder to use in this way because you have to explicitly select all containers first before running them; but the effect is ostensibly the same.

To answer your original question, use the built-in OneNote commands to selectively increase/decrease font size. You can select an entire contains by clicking on its outline; this will only focus on that container and ignore the others.

But to affect an entire page with multiple containers, the easier approach is to use the OneMore commands. Thanks.
