### ISSUE TITLE
Suggestion: Use "Labels" instead of "Tags" 

### ISSUE THREAD

**Issue by G2G2G** [stevencohn/OneMore#159]
To avoid confusion with Onenote built in tags menu, use "Labels" instead of "Tags" in OneMore's Tag Page and Find Tagged Page command names.

**Comment by stevencohn** [comment]
Yeah, I flipped back and forth on that one. It's probably the right idea. Problem is that it actually does use tags (or one anyway) under the covers so will at least show up as the "Page Tags" tag in the Find Tags panel; this gives me a mechanism for quickly searching for pages that are tagged (otherwise it might take minutes in a big notebook)

But yeah... from a user perspective, that might be the right thing to do

**Comment by stevencohn** [comment]
The OneNote tagging system, as deficient as it is, provides an extremely fast search and lookup functionality that can't be replicated with labels. Text based labels would not perform well and is too fragile to maintain fidelity across changes.
