### ISSUE TITLE
 Integrate onemore into separate tabs

### ISSUE THREAD

**Issue by TJNOV** [stevencohn/OneMore#1651]
Integrate onemore into separate tags.
I created this one by one myself. Is it possible to develop an option that can be set to this style?

![PixPin_2024-11-03_09-57-27](https://github.com/user-attachments/assets/1290a82e-516f-4026-afd2-18cc3aebd8c8)

**Comment by stevencohn** [comment]
Would it be possible to show that in English? :-)

**Comment by jasonjac2** [comment]
![image](https://github.com/user-attachments/assets/b1405544-43a7-4bb1-852f-43aa56bcb790)
a la google translate.  tags = Ribbon Tabs

**Comment by stevencohn** [comment]
Oh wow, I tried chatgpt and copilot. Didn't think of just plain old Google translate. Thanks Jason

**Comment by stevencohn** [comment]
This is what I've come up with

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/70ee112a-ad88-4377-8e85-537798ab23f5" />

**Comment by SConard** [comment]
I'm hoping you can help me. I installed the new version of OneMore and set it up to have its own ribbon tab. When I restarted OneNote, there was no separate OneMore tab, and no longer any reference to OneMore features anywhere (even in the right-click pop-up menu). I tried fixing the installation, then uninstalling and reinstalling to no avail.

In case it helps, I also have Onetastic installed with its own ribbon tab.

I'm really bummed because I love this addin.

**Comment by stevencohn** [comment]
@SConard sorry to hear that. I'm hoping it's a recently discovered problem where moving the ribbon after Help causes the add-in to fail loading. If that's the base, the easiest solution is delete your %appdata%\onemore\Settings.xml file. The do not move the ribbon after the Help tab.

If that's not the case, then can you send me your %temp%\OneMore.log file?

**Comment by SConard** [comment]
@stevencohn What an excellent start to my morning! 🤗 Everything is all fixed, and I now have a new OneMore tab. 

Thanks genuinely for your help and for your marvelous add-in.
