### ISSUE TITLE
[Hashtag] Change to new hashtag style gets added to previous one. NOT correct fully replaces old style

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1671]
# Problem to Solve

With Settings\Hashtags for “Apply custom style” you can set a style for hashtags.
BUT change to new hashtag style gets ADDED to previous one. It NOT correct fully REPLACES old style.

# To Reproduce

1. First set a style “Hashtag_BackgroundYellow” and apply it [Ctrl+Shift+F9] 
1. Then change the style to “Hashtag_TextRed” (but with background transparent) and the apply it [Ctrl+Shift+F9]. 

RESULT: Hashtags have now text red AND background yellow, but should have only text red.

#### Version
OneMore Version 6.6.1 with OneNote 16.0.18129.20158

**Comment by stevencohn** [comment]
Working as designed. There is no way to tell if the previous style was due to the hashtag scanner applying that style or the user manually applying that style. Consider the Strong style; this is the same as Bold. If you set the scanner to apply a background highlight, the user may still want to retain the Bold style if they applied that manually. It is not intended to entirely replace any and all existing styling on the text.
