### ISSUE TITLE
Command Palette – Add fuzzy search mode

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1677]
This has already been discussed in several feature requests (https://github.com/stevencohn/OneMore/issues/1581, https://github.com/stevencohn/OneMore/issues/813, https://github.com/stevencohn/OneMore/issues/658) but has been abadoned because in those use cases always an alternative workaround was found.

# New Feature
OneMore provides the great feature "command palette" (thanks for implementing it!).

Every product providing such a command palette (e.g. VSCode, products on Web/macOS/Linux/Windows) implements fuzzy search instead of strict search for the command palette (have never seen anything different, except OneMore).

**Fuzzy search**
Allows you to find commands even if your input only partially matches the command names
Sample entry: ‘Open Log File’
•	Match: olf
•	Match: openlf
•	Match: ologfi

Is it possible to implement this fuzzy search logic for the command palette (propose same logic as in Visual Studio Code)?
This would provide the de-facto standard for command palettes in OneMore.

**Comment by stevencohn** [comment]
Sorry but I still don't agree with the premise of the question. By the time you've typed "open", with the intent of typing "openlf", then the type-ahead lookup feature of the Command Palette has already narrowed down the search list quite a bit. For something like "olf" then you can still use the command alias feature. 

So I stand by the decision that the climb is not worth the view here.

**Comment by stevencohn** [comment]
Refer to #1680

**Comment by valuex** [comment]
I would like to add more comment to this proposal and I am also in favor of this feature.
Fuzzy search is of less burden to the user, compared with the alias. Because for the alias, users get to define it first and memorize the keywords.
And for these key-stroke type launchers, some of them are smart to sort the filtered results by taking into consideration of run times, the key-strokes for the corresponding command. 
The purpose of Command Palette in OneMore is to execute the corresponding command efficiently, and it is kind of like the launcher of OneMore commands. So the good features of key-stroke type launchers are worthy to be implemented.
Thanks for reading this suggestion.
