### ISSUE TITLE
Page ToC additional option +Top of Page in new container

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1712]
# Problem to Solve
Sorry for brevity, doing in a hurry.
I have just reviewed about 20 pages (older ones) and added a ToC.
To avoid breaking the author info on the page, I do the work around of:

- start a new container (Type a char in space not on any container)
- Invoice the ToC for the page | Here
- Right click container "bring to front"
- make a bit of space in the main container (just press enter between my standard top of page and the first bit of content
- - Top of page (Parent:<link>... Relevant pages: link.......)
- - first bit of content <H1> Overview
- Drag the new container into this space

I am having a bit of deja-vu, so if I have raised and this is already a request, let me know and I'll "buy you a coffee" for your wated time :-).

# New Feature/Solution
![image](https://github.com/user-attachments/assets/371e2f10-886f-4e40-86c7-75faac480dd5)

add another to the dropdown: New container - At Top of Page -In front
possibly abbreviated to "Top of Page, new container"

It would save a bit of time on the 9000 pages I need to add this to over time.

**Comment by stevencohn** [comment]
I think automating this won't work due to [this OneNote API bug](https://learn.microsoft.com/en-us/answers/questions/1119987/onenote-interop-api-updatepagecontent-changes-last). Here's why.

Your main objective is to preserve the author information by injecting a new outline at the top of the page.

We can inject a new outline at the top. But that means the existing outline(s) needs to move down by the height of the new ToC outline. Just modifying the location of an outline would overwrite all author information within that outline. While you can move outlines manually through the OneNote UI without affecting author info, it doesn't work the same through the Interop API.

**Comment by jasonjac2** [comment]
"But that means the existing outline(s) needs to move down by the height of the new ToC outline."
mmmm why?
![image](https://github.com/user-attachments/assets/6fefaf41-fb17-41ef-9d5a-0e46df394bfa)

After command
![image](https://github.com/user-attachments/assets/9875694c-d984-4446-94c4-1b55cdfb3ecc)

After I've tweaked it manually (which I will have to do when the ToC gets too large)
![image](https://github.com/user-attachments/assets/923699f5-f432-4302-b038-2dee1841579e)

Refresh  just refreshes it in place.

**Comment by stevencohn** [comment]
Well, it could just overlap the outline on top of whatever is there, like your second pic, and then let the user deal with it. Maybe another checkbox option? It would have to place it in a consistent location, regardless of where the existing outlines are located. 

Is that OK?

**Comment by jasonjac2** [comment]
"It would have to place it in a consistent location,"
"Is that OK?"
Yes definitely , but I would do something a bit like a post-it on a page, i.e. right justified on the right margin + a bit with a bit of text: "Make a space on the page and move this to where you want it". So you don't get loads of support questions about why they can't click on it.  I finally put it indented a little so you can always click on the main page and / or the ToC.
