### ISSUE TITLE
The Code block snippet should be as wide as the maximum length of the embedded text

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#186]
**Describe the bug**

**To Reproduce**
When you add a  Code block using the OneMore snippet the block gets the maximum possible width
It would be nice if it can shrink just enough to cover the text that is embedded.

**Comment by stevencohn** [comment]
It defaults the width at 600 which seems to cover all MY code because my coding style is the right way ;-)

This isn't a bug. It's working as designed which is admittedly subjective. Some people may like the box to shrink to fit the code which results in boxes of different sizes on the page, or you can set it to a reasonable width, oh let's just say 600, then all the code boxes on a page are consistent. 6 of 1, half a dozen of another

**Comment by 1001QAdotNET** [comment]
time to have a preferences menu or file :-)

**Comment by stevencohn** [comment]
To be clear are you talking about the code box or the text box? They're two commands on the snippets menu that actually run the same code - the text box just hides the title row. I'd be up for making that auto-size. But I want to keep the code block at a constant size. (And you can always resize it yourself, I'm sure you know.)

**Comment by 1001QAdotNET** [comment]
OK that would work for me, Actually the code box breaks my formats so yes please :-)

**Comment by stevencohn** [comment]
And I'd have to test what OneNote does with it. I think it will shrink if the selected text is not as wide as the page. But if the text wraps at the edge of the page, I think the box will be as wide as page.

**Comment by 1001QAdotNET** [comment]
let me try it
No it goes wide, as wide as the outline that wraps everything

**Comment by stevencohn** [comment]
with just a simple table? I'm talking about customize the OneMore Text Box snippet. Different beast

**Comment by stevencohn** [comment]
I just changed the code and tested it and it works as you would expect. 
![image](https://user-images.githubusercontent.com/9964757/107423634-9040f600-6aea-11eb-86a8-204459c6da19.png)
