### ISSUE TITLE
The addone has become unusable in certain respects and presents some strange problems

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#190]
**Describe the bug**
I am seeing slowness, OneNote gets stuck when I am using certain features of OneMore

**Expected behavior**
OneNote is reporting problems with the addon. the About and Search and Replace dialogues disappear after a fraction of second, yuo barely see them and you can only guess they are there. After pressing the buttons or using the shortcuts to bring them up OneNote becomes unresponsive and you need to kill the process in order to restart it
When I click on OneMore it needs line 5s-10 sec to open up that if it does it; sometimes it just gives a brief description of the addon and I need to click again
**Screenshots**

**Environment (if applicable):**
 - OneNote Version: [e.g. Office 2019, O365, also 32bit or 64bit?]
 - OneMore Version [e.g. 3.4 - from the About dialog or from the log file]

**Additional context**
Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log
![image](https://user-images.githubusercontent.com/17384308/107815694-bb715280-6d41-11eb-82c3-6ec9439ce771.png)

**Comment by stevencohn** [comment]
Shot in the dark but are you running AutoHotKey? It feel like a conflict with something else on your system.

**Comment by 1001QAdotNET** [comment]
No I use that rarely these days (never used it since I started using OneMore

**Comment by 1001QAdotNET** [comment]
One more thing, is the installer now asking to reboot the computer? It never did  before but it did it today

**Comment by stevencohn** [comment]
No absolutely not. Are you sure there not something else going on on your machine? I've been using it daily for the past week with this latest code and have no problems.

**Comment by 1001QAdotNET** [comment]
The slow response from the menu was there before when the addon was functional
Everything else in OneNote is functional and responsive.

**Comment by stevencohn** [comment]
The sluggishness is caused by adding OneMore commands to the Quick Access toolbar and then OneMore trying to enable/disable command items based on context. For example, some commands aren't allowed when the text cursor is on the page title. 

I have no evidence that OneMore is degrading performance from one version to the next. But I know that a couple of "power users" are adding more and more commands to the Quick Access toolbar and combined with the enable/disable feature, this is causing the sluggishness

So I'm adding an option to disable this feature. If the feature is disabled, menu items will not be enabled/disabled based on context and if you invoke one of these commands in the wrong context, OneMore will display an error dialog. 

I've proven this theory by adding a bunch of OneMore commands to the QAT, testing, then disabling the feature and testing again and can see a difference just by holding down a letter key on keyboard and watching it pause as it types out letters.

There will be a new release soon

**Comment by 1001QAdotNET** [comment]
you might have a smoking gun, let's see it
![image](https://user-images.githubusercontent.com/17384308/107883235-b89a6d00-6ebb-11eb-9ba5-7c199ef90a15.png)

**Comment by G2G2G** [comment]
> Shot in the dark but are you running AutoHotKey? It feel like a conflict with something else on your system.

Not to hijack this thread, but is there a known issue with AHK and Onemore ? I use AHK very extensively.

**Comment by stevencohn** [comment]
No that I'm aware of. Like I said it was just a shot in the dark

**Comment by 1001QAdotNET** [comment]
His shot in the dark was based on the fact that I mentioned that if OneMore can't have a macro languge by itself I would use AHK

**Comment by SnowSteve98** [comment]
I don't know if this can be related but I noticed that when I apply styles on a new document it is instantaneous, but as i add more to the page it becomes slower and slower, to the point where it takes a good 20 seconds to apply and freezes onenote while doing that

**Comment by 1001QAdotNET** [comment]
OK this 
```
the About and Search and Replace dialogues disappear after a fraction of second, yuo barely see them and you can only guess they are there. 
```
is happening when you have multiple monitors and OneNote is not on your main monitor
What I guess it is happening is that the dialog shows up on the current monitor and then it tries to move to the main monitor and it disappears in the process

**Comment by stevencohn** [comment]
v3.17 adds a new General sheet to the Options dialog to disable live dynamic menu updates (enable/disable items) for users that have added more than a couple of commands to the Quick Access Toolbar.

**Comment by CLITrees** [comment]
Yes I can confirm that speeds up the menu ...I enabled the option and I will continue to test it

**Comment by 1001QAdotNET** [comment]
Yes I can confirm that speeds up the menu ...I enabled the option and I will continue to test it
