### ISSUE TITLE
OneNote is experiencing problems with a plugin (OneMore)

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#21]
I was not able to restart OneNote (I never restarted since I installed the plugin) It asked me if I wanted to disable the plugin and I said yes and  got this message
![image](https://user-images.githubusercontent.com/17384308/83580207-6e2db780-a509-11ea-9ee1-45150d39a317.png)
After the above I started normal and I enabled the plugin back
Now I am getting these
![image](https://user-images.githubusercontent.com/17384308/83580336-d086b800-a509-11ea-8f22-f706f7aee51a.png)

**Comment by stevencohn** [comment]
Sorry I'm not sure how you got into that state. I've only seen it when seriously banging on it during development but normally it shouldn't happen. The last message means that you were trying to start it a second time even though it was already running - even if you don't see the UI. Open Task Manager and kill the process. Then you should be able to restart it.

Did you close OneNote before installing the plugin? You should. Make sure the process is gone in Task Manager. This is a 32-bit plugin so will only work with 32-bit OneNote. I haven't recompiled it for 64 bit but should be pretty easy to do.

**Comment by 1001QAdotNET** [comment]
You are correct both OneNote2016 are x32 in fact, I was wrong in my other post
All is OK now
I did notice some sluggishness when using the addon
Any chance you could add some shortucts to Custom stiles? 
If not is there any way to change the default styles? I am trying to use the mouse as little as possible while I am processing the text (reading -as in active reading)

**Comment by stevencohn** [comment]
The sluggishness is due to the fact that some of the commands in the menus first check where the focus is in the UI - if not focused on the content of the page (blinking cursor) then some commands can't be invoked so are shown disabled. The extension is seen as a COM object and there is an interop hop between the unmanaged OneNote theading model and the managed .NET extension threading model

I'll add Custom style shortcuts to the request list but I can't promise anything - remember this is a hobby project I do when I have time... :-)

There is no way to change the defaults styles. This is why I and others have built these addins to create custom styles.

**Comment by 1001QAdotNET** [comment]
No worries, nu rush we do understand the reasons
I will probably end up learning JavaScript and using the APIs, Python and Rest does not seem to cover all that I need. Not sure if there is a way to drive OneNote from Python via COM or ayhing similar. I was able to do it with Visio but I think since OneNote does not support VBA this is not possible
