### ISSUE TITLE
Launch Plugin with Shortcut or Context-Menu

### ISSUE THREAD

**Issue by smike23** [stevencohn/OneMore#215]
It would be cool if it was possible to launch a self-written plugin with a shortcut or via the context menu.

**Comment by stevencohn** [comment]
It quickly gets complicated. I could add both the My Plugins and My Snippets menus to the context menu settings but then you'd need to restart OneNote every time to change one of these lists (another limitation of the OneNote API.) I could let you add individual commands but same problem if you rename/remove that command. Regardless either way needs more logic than is worth the effort for a very slight convenience - note that both are available pretty quickly and easily off of the Favorites button.

Assigning shortcut key sequences is another mess because many people run multiple apps, including AutoHotKey, and there is a rather limited set of available keys left, not to mention the additional and complex UI needed to manage key assignment. 

Nice to have; limited value IMHO. But thanks for playing ;-)

**Comment by smike23** [comment]
ok, thanks for the quick response!
I understand the problem and agree that it is certainly not worth a major effort. 
Still, I do not give up :) Would it be possible with little effort to provide a fixed shortcut like CTRL - ALT - Shift - 1 for the first plugin, 2 for the second plugin etc. up to 4 plugins or so.
So similar to e.g. in Notepad++ for the selection of a tab (there CTRL + Num).

**Comment by stevenmcohn** [comment]
Ctrl+Alt+Shift+ 1-9 is already reserved to activate the OneMore custom styles

**Comment by smike23** [comment]
ok, what about CTRL + ALT + Shift + F1 to Fx

**Comment by stevencohn** [comment]
What type of plugins are you creating? I'd be interesting in whether they are common functions that I could incorporate into the base OneMore extension

**Comment by smike23** [comment]
I very often create meeting notes from Outlook in Onenote and always prefix the title of the page in Onenote with the date of the meeting (not the current date!) in the format YY-MM-DD.
For this I have now created a plugin (with Python) that does this automatically.

**Comment by stevencohn** [comment]
So you're adding the meeting details using OneNote's Meeting Details button? Then the plugin reads "Meeting Date" line and injects it into the title? Is that how it works?

**Comment by smike23** [comment]
Yes that is correct. Although I create the OneNote page in Outlook using the meeting notes button in Outlook, but it produces the same result.
Additionally I remove the time and change the format of the date (because its in a german date format) with the plugin.
Example: 
Title: My Meeting with Dave
Meeting Date: 10.04.2021 10:34
Title after date Injection: 21-04-10, My Meeting with Dave

**Comment by 1001QAdotNET** [comment]
So glad to see someone else using the plugin hook! I will soon get back to this too

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/blob/master/Plugins/Get-MeetingDate.ps1
