### ISSUE TITLE
Bidirectional linking

### ISSUE THREAD

**Issue by MehsEzeerf** [stevencohn/OneMore#225]
**Is your feature request related to a problem? Please describe.**
I don't think it is related to a problem unless map linked pages does this. 

**Describe the solution you'd like**
I would like any instance of text withing a page/section/notebook that matches a page tittle to be aggregated to a "reference page" or container on teh page which is being linked. 

really wanting to attempt to mimic on some level the functionality of www.roamresearch.com

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by that0n3guy** [comment]
Oh yeah, this would be amazing.  

I thought I would expand on how this might work... with mockups:


## Example of how this would work
Page A:
![image](https://user-images.githubusercontent.com/113870/117511811-fefbe700-af53-11eb-8c6f-7aa6448d2fda.png)
* this page contains a link (link 1) to another onenote page (page b)


Page B: 
![image](https://user-images.githubusercontent.com/113870/117512432-34ed9b00-af55-11eb-825f-e86831f5f547.png)
* this page had some content on it already... but since I added the link on Page A, OneMore has added a list of linked references section.   
 
#### Object linking example
It not only links to the page, but to the specific object that does the link:
Clicking here:
![image](https://user-images.githubusercontent.com/113870/117512606-8c8c0680-af55-11eb-9096-7fc9d0796a05.png)

links here:
![image](https://user-images.githubusercontent.com/113870/117512660-a88fa800-af55-11eb-9819-a6bbb161622b.png)
(this is normal object linking functionality in onenote)

**Comment by stevencohn** [comment]
will be in next release

**Comment by that0n3guy** [comment]
Ohh thats fun.

**Comment by MehsEzeerf** [comment]
Obviously this is a side thing so all bets are off but what kind timeline
for the next release are you thinking?

**Comment by MehsEzeerf** [comment]
Also,  I was thinking more like hijacking the existing page creation feature if possible so. [[ info ]] creates a new page or creates a reference to the existing page.  Then if the page  [[ info ]] gets updated on its actual page to [[ not info ]] it would updated all the links that it goes to?  This is really a nich thought process though based on how I use OneNote not sure how well it scales out or features could be added.

**Comment by MehsEzeerf** [comment]
ahh just saw that I was late to the party with that last contribution.

**Comment by stevencohn** [comment]
A couple of days of testing and refinement...
