### ISSUE TITLE
MIND MAP for One Note

### ISSUE THREAD

**Issue by Raquo116** [stevencohn/OneMore#232]
![mind](https://user-images.githubusercontent.com/13005473/121894121-63bd1500-cd3c-11eb-949e-2d795c7093e5.jpg)
Is it possible to have this onenotegem macro in OneMore next update. It Will be very beneficial for the student.

**Comment by stevencohn** [comment]
This has been requested before and I've put it off because it's not a trivial thing to do. OneNote is note suited to managing this sort of drawing, mainly because it doesn't have the concept of "connector lines" between shapes. Gem gets around this by using content elements (gray bordered regions), storing metadata in them about connections, and then forcing you to click a refresh/redraw button to redraw all the connectors after you've shuffled things around on the page. So it a "poor man's" mind map at best. It's really more of a "follow-me" drawing helper. 

Unfortunately, I wouldn't be able to improve on this and I'm not sure it's worth the effort. You may be better served by find a free open source mind map tool and then pasting exported images or screen captures into OneNote.

**Comment by Raquo116** [comment]
ok, thanks for your suggestion and keep doing the great work your doing.
