### ISSUE TITLE
Problem with the Italian keyboard and the shortcut Ctrl + Alt + Plus for "Increase Font Size"

### ISSUE THREAD

**Issue by gpbicego** [stevencohn/OneMore#305]
**Describe the bug**
The shortcut Ctrl + Alt + Plus prevents the insertion of the character ']' with the Italian keyboard.

**To Reproduce**
1. Use an Italian keyboard
2. Press the keys AltGr + ]
3. Instead of character ']', the page font size are increased

**Expected behavior**
Insert character ']'

**Comment by stevencohn** [comment]
So after a quick check, I found two things. First, Ctrl+Alt+Plus isn't exactly correct; on a US keyboard, it's actually Ctrl+Alt+Equals. This is because Ctrl+Alt+Plus which mean also using the Shift key which is the built-in OneNote sequence to zoom the entire page.

Second, when I press Ctrl+Alt+Equals and then press ], it correctly inserts the right-square-bracket. When I press Ctrl+Alt+(Shift)+Plus and press ], then it inserts an equals sign!

So are you actually pressing Ctrl+Alt+(Shift)+Plus? Or just Ctrl+Alt+Equals?
