### ISSUE TITLE
Search to Tag Feature?

### ISSUE THREAD

**Issue by Arcyne** [stevencohn/OneMore#404]
**Is your feature request related to a problem? Please describe.**
I would like to make tagging existing pages easier.  

**Describe the solution you'd like**
I would like to be able to use the search to apply tags in a similar way to the search to move feature works.   +1000 karma if you implement an autotag functionality based on NLP.  :-)

**Describe alternatives you've considered**

**Additional context**

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by zhongguocn** [comment]
Thank you for fixing the bug in time.

But there is a small problem.Using the OneMore to add a tag, there is no problem embedding the page.
Because onemore has no tag management function and multiple tag condition search function, I have to use another plug-in tool.
When using the OneNoteTaggingKit to add a page tag, the embedded page still displays the tag instead of the page content.
https://github.com/WetHat/OnenoteTaggingKit/releases

**Comment by stevencohn** [comment]
I can't fix that. OneNoteTaggingKit doesn't mark the outline that contains its tags in any way so I can't tell the difference between its tags and normal content on the page. OneMore looks the same but it uses an internal marker to identify the tag outline as special and knows to skip it for operations like the Embed feature.

**Comment by stevencohn** [comment]
Having said that, what does OneNoteTaggingKit give you that OneMore's tagging feature does not?

**Comment by zhongguocn** [comment]
OneMore is my favorite plug-in tool, but its tag function is really a little simple and inconvenient to use.

1.Tag cannot be managed
When I have dozens of tags, it is difficult to manage. It is necessary to find or rename an existing tag. When the tag is modified, all the tags on related pages can be renamed automatically.

2.Add tag
When adding tags to a page, you should have the function of automatically filtering existing tags. For example, I have set tags such as "100", "200" and "300". Now I want to add a new tag to a page.  When I enter "00", it's best to automatically filter out the tags of "100", "200" and "300" in the alternative box。 This can provide efficiency.  More importantly, it will avoid setting several tags with similar names.

3.Find tag
If page A has a tag "A, B, C", page B has a tag "A, D".  When I search tag "A, B", I need to accurately search page A, not page A and page B.  That is, OneMore searches for multiple tags with "or" instead of "and". This is very important when you have hundreds of pages.

4.Save tag search results
We often search some specified tags.  It will be very useful if we can save multiple search results. That is, when I search some pages through several tags, I will hope to save the links of these pages to a new page for easy use. Even further, you can add a refresh button on the search results page.  When the user clicks refresh, the search results will be refreshed according to the search conditions.

If the tag function of OneMore can add the above functions, it will be perfect.

Thank you again for developing such a useful tool.

**Comment by stevencohn** [comment]
Release 4.17 addresses #3, adding an Any and All operator to the search dialog.

The remaining items have been split off into a separate issue, #463
