### ISSUE TITLE
v4.15 MSI

### ISSUE THREAD

**Issue by NoralK** [stevencohn/OneMore#412]
**How can I help you?**
Ask away...

Is there going to be a x86 MSI for v4.15 ?  About->Update is not updating x86.

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
I didn't plan on creating one. Is this because you have an x86 machine or because you have OneNote 32-bit?

An x86 MSI would only be needed if you still have an x86 machine.

It is NOT needed if you have an x64 machine, regardless of whether you have OneNote 32-bit or 64-bit. The x64 (64-bit) MSI will work in both of those cases.

Let me know and I'll create one for you. (Secretly, it was a test to see if there were still people out there still on x86 machines! ;-) )

**Comment by stevencohn** [comment]
Oh sorry, also which version are you trying to update? 4.13.1 broke the update and 4.14 fixed it. If you have 4.13.1 just uninstall it and then you can install the latest.

**Comment by stevencohn** [comment]
https://github.com/stevencohn/OneMore/releases/download/4.15/OneMore_4.15.1_Setupx86.msi

:-)

**Comment by NoralK** [comment]
I have v4.11 and it will not update.  I will use the x64 installer.

Yes, I have 64-bit OS but x86 OneNote.

**Comment by NoralK** [comment]
FYI - I just tried to install v4.15.1 x86 and it would not show up in x86 version of OneNote 365.  Using the x64 package did add it back in.
