### ISSUE TITLE
Installation problem, error message

### ISSUE THREAD

**Issue by nofolojts** [stevencohn/OneMore#458]
**Description**
The program does not install.

**Steps**
Followed the wiki: 

0. From an admin account...
1. Closed OneNote and Send To OneNote
2. Downloaded the x64 installer and ticked unblock in properties.
3. Ran the installer, got the "allow this program to..." prompt. clicked through the installer
4. Got the error message below
![image](https://user-images.githubusercontent.com/28601341/154956825-f0e722cf-3202-4b5c-8243-e419c8cb65aa.png)

**Environment:**
 - OneNote Version: O365, 16.0.14827.20198
 - OneMore Version: 4.16

I hope it's just something being strange on my end or my haphazard reading :) Let me know if I can provide further useful info.

**Comment by stevencohn** [comment]
If this file exists, can you please copy and paste it here: %temp%\onemoresetup.log

**Comment by nofolojts** [comment]
No such file unfortunately 🥲

**Comment by Robolin** [comment]
I'm seeing the same error I think, our corporate Antivirus throws an error, won't install it.

Trying to extract it using 7Zip fails too:

OneMore_4.16_Setup64.msi
Icon._853F67D55F05449430E7E.exe
Can not open the file as [PE] archive

**Comment by tinysnails** [comment]
-------------------------------
OneMore installer running as user NT AUTHORITY\SYSTEM (S-1-5-18) elevated

Register... version 4.17

ShutdownOneNoteAction.Install ---
ONENOTE process not found

ProtocolHandlerAction.Install ---
step 0: opening HKLM:\Software\Classes\onemore
step 1: setting properties of HKLM:\Software\Classes\onemore
step 2: opening HKLM:\Software\Classes\onemore\shell\open\command
step 3: setting properties of HKLM:\Software\Classes\onemore\shell\open\command
verified: key created HKEY_LOCAL_MACHINE\Software\Classes\onemore\shell\open\command

TrustedProtocolAction.Install ---
translating user user to SID
registering trusted protocol for user user (S-1-5-21-147214757-305610072-1517763936-6666111)
defaulting Office version to 16
step 4: opening HKCU:\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\onemore:
key already exists

EdgeWebViewAction.Install ---
error registering

**Comment by StephenMSmith** [comment]
I have no problems installing but this error when I launch OneNote from $505 moved to this thread):

Message: Unable to cast COM object of type 'Microsoft.Office.Interop.OneNote.ApplicationClass' to interface type 'Microsoft.Office.Interop.OneNote.IApplicationCOM'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{452AC71A-B655-4967-A208-A4CC39DD7949}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
Source: mscorlib

I repaired Office several times but no go.  However, I just installed on my laptop which runs same Office 2016 and no problems at all.  So it's clearly this particular Office 2016 install on my desktop.  I haven't uninstalled and reinstalled the whole Office suite and would rather not as it's part of my old MSDN license.  

What else could this be?  Could this be registry security?  I could try running RegMon and FileMon to see if any useful from there.  Is the type library/DLL that is the problem here mscorlib?  If not, what might it be?

**Comment by stevencohn** [comment]
Yup it's all kind of the same problem over and over again. Unfortunately, I haven't been able to build a system on which I reproduce any of it yet. Still trying...

**Comment by stevencohn** [comment]
And yes, any help would be greatly appreciated.

**Comment by StephenMSmith** [comment]
Happy to help any way I can.  Is their any output from any of the SysInternals tools I can get for you that would be useful?

**Comment by StephenMSmith** [comment]
I had some fun trying to figure out what the heck was happening in Visual Studio and the SysInternals tools but no go.  So I did a complete uninstall of Office 2016 and then a clean install of Office 2021.  Problem gone.  OneMore works perfect now in OneNote.

**Comment by DendrocoposMajor** [comment]
The other day, I wasn't really paying attention, again, I might add. Trying to install the OneMore extension yet again in the faint hope that "it will work this time", by mistake? I started installation of the 64-bit version. I've got 32-bit OneNote installed so the 32-bit OneMore(x86) ought to be the proper match? Anyway, the 64-bit installer went through all the motions and ran to a successful end. OneMore is now installed, and it actually seems to work. Well, as far as I've had time to try it out, anyway.

**Comment by stevencohn** [comment]
As per the [installation instructions](https://github.com/stevencohn/OneMore#install), choose the installer that matches your bitness of Windows. The installer does not need to match the bitness of OneNote. This is because the installer will set up Registry settings based on x86 or x64 Windows.

**Comment by DendrocoposMajor** [comment]
It was unfortunately an easy mistake to make. Most programs expect extension to be the same "bit-size" be it 32- or 64-bit.
And several Office (Word,Excel, etc.) extensions expect this to match in order to work.
That said, I am happy that I what I thought was a mistake made it work as it would and should have all along...
Really irritating though. ;)

**Comment by stevencohn** [comment]
The installer _should_ abort if it recognizes you're using the wrong installer based on the architecture of Windows. Other than that, I've tried to explain in clearly in the installation instructions. Not much more I can do unfortunately.
