### ISSUE TITLE
Enhancement to Linked References

### ISSUE THREAD

**Issue by Meh-S-Eze** [stevencohn/OneMore#481]
**Is your feature request related to a problem? Please describe.**
I would like the linked references function to have an option to return results with paragraph level links for each intance that the page is linked on anyother page.

**Additional context**
If multiple links on the same page but different boxes it only shows one link.

Input
 
![image](https://user-images.githubusercontent.com/66741217/158702131-328eb0ea-c31a-40da-a69a-e37e12783ad1.png)

Result
 
![image](https://user-images.githubusercontent.com/66741217/158702152-ca342608-ea0d-44be-b8c3-7d49a449c3a3.png)

Expected/Desire result

 
![image](https://user-images.githubusercontent.com/66741217/158702166-0bee9333-6b98-4c59-bfdb-e79eb4f2a90d.png)

OR
![image](https://user-images.githubusercontent.com/66741217/158702175-31ddf885-6809-4e65-8d08-2a2fc84075ea.png)

**Comment by stevencohn** [comment]
This command currently uses the built-in OneNote search which in turn relies on Windows Search and indexing. This is very fast and efficient. But it does not return paragraph-level granularity. In order to do that, 

OneMore would have to fetch and search each page individually itself which can take minutes when done across very large notebooks.

**Comment by MehsEzeerf** [comment]
What about container level granularity?

**Comment by stevencohn** [comment]
Same.
