### ISSUE TITLE
Supplement to the conflict between Onemore Add-in style and Onenote's own style

### ISSUE THREAD

**Issue by codercplus** [stevencohn/OneMore#497]
**Describe the bug**
As #496 can't be reproduced , I will  add more key details. Whole process screen recording is as following:

![ani3](https://user-images.githubusercontent.com/63757163/166108175-190ea20f-3d0a-4840-94ab-8228b5803791.gif)

**To Reproduce**
See the above recording  for details. Here are  some key-points.
(1) . The order in which the styles are arranged has a key impact on the results. You need to put the style you want to apply (style-2) in the second position. Never put it to the first place.
![Snipaste_2022-04-30_21-59-23](https://user-images.githubusercontent.com/63757163/166108556-cbddf749-b9b8-432f-b41e-6bd545ec3bca.png)

(2). The details of Style-2 are as following.
![Snipaste_2022-04-30_21-59-59](https://user-images.githubusercontent.com/63757163/166108592-de6c4b60-5f6a-42d0-8e1f-b6b73ba85215.png)

(3). The font-size of customized style (in the above image) is VERY VERY IMPORTANT. **It should be exactly the same as the font size in the options of OneNote software**. Only being setted to the same font size can the bug be reproduced.
![Snipaste_2022-04-30_22-11-01](https://user-images.githubusercontent.com/63757163/166109035-b777431a-fa94-4ce7-b71c-433ad121bdbf.png)

**Environment:**
 - OneNote Version:O365,64bit
 - OneMore Version: 4.17

**Comment by stevencohn** [comment]
This cannot be corrected. However, I will add a note to the Wiki page to explain case and why it should be avoided.

Note to myself: This is due to the fact that OneMore styles are not tagged as unique entities and are instead inferred by comparing properties to determine closest match. So two styles with the same visual properties (not including the IsHeader flag) are treated the same when using the Apply command. There are no XML element attributes that can be applied to content to make style assignments more explicit; need to continue the current inferencing logic.
