### ISSUE TITLE
When the Style Type is Heading and Font size is the same as Onenote options , the result may be wrong

### ISSUE THREAD

**Issue by codercplus** [stevencohn/OneMore#498]
**Describe the bug**
Creat two custom styles, the only difference between them is the Style Type. One's type is Heading, and the other's is Character. 
However, the result in font-family and font-size maybe far difference. Especially when the font size in onenote options is the same as in custom style.

**To Reproduce**

1. Go to 'File→Options', Switch to  'General' tab , **set the 'Size' to 11pt** and 'Font' to Arial.
![Snipaste_2022-05-03_13-42-41](https://user-images.githubusercontent.com/63757163/166409121-01d7a4b7-b1dd-4162-846e-c5ba6473c96e.png)

2. Go to Onemore→Custom Styles, click 'Edit Styles→new' to creat two new styles , the details are as following.
![style1](https://user-images.githubusercontent.com/63757163/166409413-879509cd-e85e-4b7c-b2d3-c4671ca4de6c.png)
![style2](https://user-images.githubusercontent.com/63757163/166409417-21dbab78-c186-4dc2-93d1-4092b923b1ab.png)

3. Just type two lines of text.
![Snipaste_2022-05-03_13-51-05](https://user-images.githubusercontent.com/63757163/166409735-39865fe4-80fb-482f-9989-73d96c2c1452.png)

4. Apply 'Style-test-1' to the first line of text, and 'Style-test-2' to the second line of text.
![Snipaste_2022-05-03_13-50-15](https://user-images.githubusercontent.com/63757163/166409664-fda5582a-6c97-4e65-832a-8581a5488f23.png)

**Expected behavior**
For the first line of text that is applied by 'Style-test-1', the font family should be 'Arial' and font size should be 11pt. However, the unexpected result is that font family is 'Carib' and font size is 16pt.

**Environment (if applicable):**
 - OneNote Version: [O365, 64bit]
 - OneMore Version [4.17]

**Comment by stevencohn** [comment]
This cannot be corrected. However, I will add a note to the Wiki page to explain case and why it should be avoided.

_Note to myself_: This is due to the fact that OneMore styles are not tagged as unique entities and are instead inferred by comparing properties to determine closest match. So two styles with the same visual properties (not including the IsHeader flag) are treated the same when using the Apply command. There are no XML element attributes that can be applied to content to make style assignments more explicit; need to continue the current inferencing logic.
