### ISSUE TITLE
Ability to save custom snippets with collapsible paragraphs

### ISSUE THREAD

**Issue by vfxturjo** [stevencohn/OneMore#558]
**Is your feature request related to a problem? Please describe.**
I tried to **combine** the **information block** snippet that comes with OneMore, with **expand/collapse** snippet. Then i tried to save it as a custom snippet, so i can re use the collapsible information block.
But when I try to use it, it doesn't have any "(expand)" or "(collapse)" button. 

I tried to understand how "(expand)" or "(collapse)" button works/comes from. After finding it, 
> <one:OE explicitExpandCollapseEnabled="true" ...............

I thought maybe i can paste the code to the snippet file to manually force it to load the tag in the paragraph.
but i can't. I mean I don't know how to... they dont look similar syntax. (I m noob, sorry)
![image](https://user-images.githubusercontent.com/44445014/184669922-617f244f-06df-4b94-b254-2d85926d0c4a.png)

**Describe the solution you'd like**
A way (button/toggle/settings) to enable saving snippet with the tag -> explicitExpandCollapseEnabled="true"
So that I and people can save collapsible things as snippets

**Describe alternatives you've considered**
A workaround to manually add some code in the snippet file. just as I was trying.

**Additional context**
![image](https://user-images.githubusercontent.com/44445014/184670953-7b31fe7d-9cf1-4bfc-a592-3b09d6155a4f.png)

**Comment by stevencohn** [comment]
Snippets are stored as HTML and HTML doesn't have a corollary to the collapsible attribute found in OneNote. 

OneMore uses HTML to persist the snippet because it's very simple to copy/save and then paste HTML in OneNote. It would be extremely complex and a large project to attempt to save the OneNote XML and then inject that intelligently into a multitude of contexts on any OneNote page.
