### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Benjamin-Watson0** [stevencohn/OneMore#652]
**How can I help you?**

![图片](https://user-images.githubusercontent.com/112467275/194226573-47768d7d-1ba0-4bbb-9d38-919af65929dc.png)

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
Did you run the installer as an admin user? You cannot run it from a normal user (non-admin) account.

**Comment by stevencohn** [comment]
I was able to reproduce this by creating a D drive from one machine, mounting it to a second machine and trying to install OneMore on that D drive on the second machine. It appears to be a security ID, disk ownership problem. Investigating...

**Comment by stevencohn** [comment]
OK, I've confirmed that this is an elevated permissions issue. I'm not sure why the installer is not providing a better info message (this is internal to Windows' installer and not something I or OneMore have control over.)

You can work around this by opening an administrative command prompt and running the MSI from there rather than double-clicking it from a normal-user File Explorer. Give that a try and let me know.

**Comment by stevencohn** [comment]
Closing for now
