### ISSUE TITLE
Any chance you could be interested in a browser addon like "send to onenote" but making it much better ?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#669]
Is that something that could be integrated in the OneMore package and improved with functions like add tags to the imported page ?
This could be very simple if the OneMore import code could be called from the browser. 
I am just asking because sometimes I am in the browser and it would be much easier to send the page from there than to switch to OneNote and do the import from there. BTW -adding tags on import could be a nice improvement there

I suspect the JavaScript OneNote APIs might come handy here for the browser addon

**Comment by stevencohn** [comment]
2... maybe 3% chance. I've looked into this in the past and it's an entirely different project that I don't really have the appetite for at least at this time. 

This could not be deployed/installed along with OneMore because that would presume the user has enabled side-loading in either Edge or Chrome which is off by default. The browsers encourage addons/extensions to be published to a known repo/store that they trust - and that's a whole workflow in and of itself.
