### ISSUE TITLE
Feature request: Import PDF and EPUBs to OneNote

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#67]
I would like to be able to import PDFs and EPUBs into OneNote
I am not sure what language is this written in but maybe you can fork and include this in OneMore

https://github.com/OneNoteDev/OneNoteConversionTool

**Comment by stevencohn** [comment]
That library is old and hasn't been touched in a while and I'm not really interested in maintaining someone else's code base. I write OneMore as a hobby and to write my own code. But I also see this as a low priority request because there's always a workaround of linking the files into a note - not perfect, but it works. So I'll put this on the shelf for now. Thanks for the ideas, keep them coming.

**Comment by 1001QAdotNET** [comment]
the idea is not to link them but to add them to one note in order to do active reading (restructure the layout, add text annotations highlight , add comments and so on)

**Comment by stevencohn** [comment]
I understand.

**Comment by stevencohn** [comment]
I've done some poking around and there's no good way to convert PDF to editable content without loosing all formatting; there are free-use libraries that just scrape the text but you could just copy/paste from Adobe Reader to do that.  The OneNoteConversion tool you reference above rasterizes PDF pages into images so you loose the ability change or annotate. 

There are commercial license libraries but I can't use those without charging for OneMore. And there are online services that you can use to pump files through and they spit out HTML but I wouldn't trust them with anything remotely sensitive.

The OneNoteConversion tool does convert EPUB to HTML so that's possible, although I'm focusing on other features so not necessarily probable.

**Comment by 1001QAdotNET** [comment]
I have also tried Adobe Acrobat -Save as Word Document but it is not spectacular
If the PDF is a presentation then the result is a disaster

One good contender for this is Calibre that does PDF to EPUB and from there using the above to go to HTML but the EPUB conversion is bad
