### ISSUE TITLE
Add keyboard/command to decrease images to fit within a preset width

### ISSUE THREAD

**Issue by stevencohn** [stevencohn/OneMore#681]
_From user CC..._

Hi, thank you for your great Onemore plugin, I love it. 

Is there a way to have a keyboard shortcut in order to always decrease the size of the pictures I copy/paste in OneNote to 500 width? I know is it available in OneMore/Image/etc... But I would like to do it more simply. 

Thanks for your help.

**Comment by edogd** [comment]
I tried doing this with an AutoHot key macro.  Unfortunately the dialog box used for image resizing in OneMore does not fully work with keyboard only navigation.  Thus thre are certain fields in the dialog box you cannot access via keystrokes.  So I was not able to make the macro.  Maybe if the resizing dialogs could be improved to fully support keyboard only navigation then a solution like using AutoHotkey would better because then you can customize the exact way you want to the image resized?

**Comment by edogd** [comment]
You found it, I was not able to select the radio buttons for Absolute or Preset.

**Comment by stevencohn** [comment]
So here's the rub: If no image is selected, the resize dialog morphs itself depending on how many images are on the page. It knows if there is one image or multiple. If there is one image, it will assume the normal mode shown here:

<img width="515" alt="image" src="https://user-images.githubusercontent.com/9964757/201433972-47d2d8a4-e857-475d-8f4c-5cf40bad08d4.png">

If there are multiple images, or more than one image is selected, it morphs into this:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/9964757/201434155-c7fd527d-d876-4e02-a5ea-402fae5574b0.png">

And you can see the Option to "not enlarge smaller images", which is really the mode you want in this case, I believe.

If you can start off with no images selected, or all images selected (you can use OneMore's Edit/Select all images) then you should be able to use AutoHotkey

**Comment by stevencohn** [comment]
closing as stale. presume answered by above comment.
