### ISSUE TITLE
Question regarding the format of the XML file that is expected to be returned when calling an external plugin

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#69]
If my plugin removes the xmlns namespace which is inherited downstream by all the children nodes and it process the XML needed and then it returns the file without that will OneNote be bothered by this ? (I am still learning how to remove it so I can't test directly)
Attempting this on the Show XML editor worked, OneNote added that back

I guess a more generic question is how much can I strip down from the XML filed passed to me by OneMore before returning it to OneMore? I would like to get rid of attributes  like lastmodified, author and so on

**Comment by stevencohn** [comment]
You need to preserve and work with the one namespace. 

The EditedByAttributes (like lastModifiedTime) are mostly auto-managed by OneNote. There's no reason to strip them out; OneNote is just going to add them back in. For new elements that you generate, you do not NEED to add those attributes since OneNote will add them automatically.

**Comment by 1001QAdotNET** [comment]
Where can I read about the meaning of the tags used in the OneNote XML format
I can't make sense of OE ...Outline E....???

**Comment by stevencohn** [comment]
The \Reference folder has the .xsd file.
The OneMore\README.md file has links to the OneNote Application Interface Reference and the Office File Formats and PDF downloads
