### ISSUE TITLE
A simple gantt chart would be nice.

### ISSUE THREAD

**Issue by ianzhang1988** [stevencohn/OneMore#694]
**Is your feature request related to a problem? Please describe.**
Problem that gantt chart solved. Time management and virtualization. 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/25296413/197489574-331ae4c8-af4f-4b22-b7a6-48de5ecffdb3.png)

A adjustable table maybe.

**Describe alternatives you've considered**
Tried using calendar, but it's just not the same.

**Additional context**

**Comment by stevencohn** [comment]
I appreciate the sentiment. It has been requested before. Even simple functionality would pale to what any third-party Grantt Chart applications out there (Microsoft Project?) already provide and not be able to offer any workflow advantages over these battle-tested and hardened alternatives.

One of the biggest challenges is that OneNote doesn't support merged table cells or any way of creating bar charts that can overlay a grid like you've pictured above. So that means drawing a picture based on some data. And entering that data would be tedious and error-prone or require substantial application work to guide the user. It's way beyond the scope of what OneMore is trying to accomplish.

**Comment by ianzhang1988** [comment]
I see. 

Is there a table generator or template? I can paint the grids myself. 
I do this by hand now, some automation would be nice.
