### ISSUE TITLE
Make Title Case even more useful

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#753]
**Is your feature request related to a problem? Please describe.**
I put my cursor in the page title and ran the "to title case" command and nothing happened.

**Describe the solution you'd like**
1. I would like to be able to define a keyboard shortcut for the "to title case" command
2. If the text selection is empty then I would like commands that change case to work on the entire paragraph, like heading styles do.
3. I would like to be able to set an option for custom styles (at least for heading/title styles) to apply title case at the same time as the rest of the style.

In my current usage, OneNote always capitalizes the first letter of a paragraph. When I am typing a heading, I have to make sure to do all the rest of the determining which words should be capitalized and then actually typing them in caps. And finally, I use the OneMore shortcut to apply the proper heading style.

This is a great example of how a simple change could greatly improve efficiency. It is like starting with OneNote autocap and multiplying times 10.

It appears that "to title case" is really just capitalizing each word and not using the publishing definition of title case. I'll add a separate request for that.

**Comment by stevencohn** [comment]
The to-case commands are currently restricted to only the body of the page and don't work on the header. I agree that could be changed.

**Comment by stevencohn** [comment]
### Changes
* To Title Case can now be assigned a keyboard shortcut
* To Title Case, To Lower, and To Upper can be applied to page title
* Other commands not previously in Keyboard Shortcuts settings are now also available for assignment (those that can be)

### Note
* To Title Case will continue to work like To Lower and To Upper; it applies to the current word if no selection range, otherwise it applies to explicit selection range. This strategy duplicates the implementation in Microsoft Word.
* Adding casing option to Edit Styles dialog will be done under a separate ticket
