### ISSUE TITLE
Build a Smoke Test Script

### ISSUE THREAD

**Issue by stevencohn** [stevencohn/OneMore#768]
## What is this?
To improve the quality of each release, create a suite of tests that can be run as a whole or selectively to demonstrate that the changes within a release are working as intended and have not disrupted existing behaviors.

## What help is needed?
* Write test protocols. Currently, working through them in a top-down fashion within the Commands folder, starting with Clean commands, Edit commands, Extra, File, etc. Since each folder is a separate section.one file, they can be done independently.
* Executing test protocols. Test will be chosen based on risk and proximity to blast radius of recent changes. Not all tests will need to be executed for each release. Depending on the number of tests, an announcement will be made in a "pre-release" release as to whether help is needed

## Strategy
For each xCommand.cs class under the /Commands folder, create a test protocol that consists of
* The class name as the title
* The description of the behavior of the command
* Steps describing manual execution of the test(s) that demonstrate behavior
* Note any constraints, e.g., "Minimum allowed font size is"
* Sample content that will be affected by the test

## Implementation
Initial implementation will be entirely manual without any programmatic testing or automation frameworks. The test steps should be clear and easy enough for anyone to walk through and provide guidance on how to confirm the expected behaviors

Test protocols will be captured in a OneNote notebook
* A section will be created for each folder under /Commands
* A page will be created for each xCommand, similar to the picture below

> <img src="https://user-images.githubusercontent.com/9964757/204534969-435e6f8e-34d4-43de-afc1-f967213d4e13.png" width="500"/>

_Note that the checkmark is a simple indicator that the protocol is complete and the command is working as expected; this is an internal flag for OneMore developers to know that no changes are required to "fix" behavior._

In cases where a behavior does not function as expected, modify the page similar to the following with a red X and a red note explaining what needs to be fixed. Defect tickets may be raised using this info

> <img width="500" alt="image" src="https://user-images.githubusercontent.com/9964757/204883550-43f01116-20da-405e-ab76-5115e4436d30.png">

## Out of Scope
The initial implementation are simple directives, not software specifications. So Gherkin-style executable specifications are not required. UI automation frameworks will not be used. It may be possible in the future to automate exec specs via an automation framework, similar to White or Winium.

**Comment by 1001QAdotNET** [comment]
you mean something like the testing used for Test Driven Developement ?
I guess that means C#, the language used for this project

**Comment by stevencohn** [comment]
Not TDD, but rather E2E... To begin, I'm created a Test Suite notebook with a section per category and a page per command with individual instructions (a "script") to guide a manual walk through of every command. I can then run the tests for high-risk commands within the blast radius of any recent changes.

Eventually, this could be automated, but that's a ton of work that, well, I won't get paid for.

Example

<img width="528" alt="image" src="https://user-images.githubusercontent.com/9964757/204393986-80522c92-9664-4ab4-b1a0-ecc28bcbae61.png">

**Comment by 1001QAdotNET** [comment]
So you need some sort og GUI automation. 
Since this is not Web GUI I guess you need to use a scripting like AHK (AutoHotKey) ...is that what you have in mind ?

**Comment by stevencohn** [comment]
No there are UI Test Automation suites and frameworks out there like Winium, Appium, White and others.

**Comment by stevencohn** [comment]
The Clean.one section here is what I'm starting with. https://github.com/stevencohn/OneMore/tree/main/OneMore/Testing/OneMoreTests

Need one of these for each folder under the Commands folder
https://github.com/stevencohn/OneMore/tree/main/OneMore/Commands

**Comment by 1001QAdotNET** [comment]
So you need the text sample and the test protocol as well to go with that.
If it is a protocol you need a protocol description (formal pseudo code for the protocol) or better the synthax of that protocol if it already exists

AHK is good because you can record the script. 
DOn't know about the other you mentioned, Testing is an entire domain by itself

Do you need the protocol in pseudo code ? I would say it would be easier for everybody to help if you provide a utility of your choice like AutoHotKey that has a recorder. Our task would be to implement that on a standard text 
We need a reference text (Lore ipsum like) that will grow (you edit one file) and each one of us can pick a scenario and record the test. 

Then you can validate and accept it in the collection

**Comment by jasonjac2** [comment]
@stevencohn I get it.  I guess you would need an "experimental build" and a way of seeing who has executed which "script" along with some basic info, e.g. something from the log file that has bitness of OS / versions / ....., then when you put out a call, we can test bits of it based on your scripts and you can build up a base of reliable / unreliable human-bots. 

I'm also happy to help with automated test, although my experiences are: Smartbear - TestComplete, which I used many years ago.  You would click / keyboard execute your test, then I would go in and edit the script, so instead of running it just once, it could be parameterised (and in our case, visit every part of the system for every client and make some changes).  I am very interested in restarting auotmated GUI testing, but haven't done my homework on a free / cheap / Open Source Win GUI tester that allows scripting or automating.

**Comment by stevencohn** [comment]
I hate the Close button

**Comment by 1001QAdotNET** [comment]
I am useless when it comes to these things but I wanted to make sure I get the idea before I say I can't help

**Comment by stevencohn** [comment]
Here's a link to the Smoke Test notebook (read-only) on onenote.com - https://1drv.ms/u/s!ArTUF0U30CVpg8lnWV_-ee6DvD9QyA?e=VHZirT
