### ISSUE TITLE
Any idea why exporting text from Notepad++ with formatting (RTF or HTML) ruins the EOL and or the TABs?

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#77]
If I have this text in Notepad++
```
test   #comment
	test2 #comment2
		test3 #comment3
```
and I select Python as language I get the comments colored (dark green)
Then if I use the Notepad++ Plugin NppExport that allows me to copy text in HTML or RTF to clipboard
If I paste that text in Wordpad the formatting and the tabs are preserved
If I paste that text in OneNote it will look like this
![image](https://user-images.githubusercontent.com/17384308/96731244-088d7b00-1385-11eb-870a-21090d23811c.png)
 The expected result is this
![image](https://user-images.githubusercontent.com/17384308/96731292-16db9700-1385-11eb-8b21-37d7e1ca53f8.png)

Is this something that can be fixed via OneMOre

Also trying to move the formatted text via WordPad and copy and paste from there is not preserving the format

**Comment by stevencohn** [comment]
Used OneMore's Paste Rich Text feature. 

I was able to repro and prove that going from NppExport RTF to clipboard, to OneMore's Paste Rich Text, preserved layout

**Comment by 1001QAdotNET** [comment]
In my case it turns the tabs into spaces and I am not able to collapse the indented paragraphs
You are right it preserves the formatting but it turns the tabs into spaces

**Comment by stevencohn** [comment]
Hm, let me take a look. OneMore is the guilty party here, converting your lovely tabs to nasty spaces because OneNote actually doesn't support tabs; it either converts them to indents or generates a table column. If there are tabs at the beginning of a line, I might be able to render them as indentations. If they are in the middle of text, though, I think it still makes sense to convert them to spaces. 

So it adds a bit of complexity to the Paste RTF command but I'll think about it...

**Comment by stevencohn** [comment]
Yeah, it would involve quite a big rewrite of the Paste RTF command and I tend to think it's not all that important in the long run. I'm presuming you're using OneNote to jot down snippets - but OneNote of course is not a programming language editor. You can still easily cut/paste snippets into a real programming editor and reformat spaces to tabs - most have that functionality. And actually, by removing the tabs and converting to indents, then you'll loose the layout when you paste into a programming editor anyway so ya just can't make everyone happy!

**Comment by 1001QAdotNET** [comment]
No code snippets are not my concern.
Being able to copy native indentation of a text I am reading is crucial for the readability of that piece of text and by indentation I mean turn the RTF indentation in OneNote indentation so I could collapse paragraphs or chapters of the text I am reading

IF you could only turn any number of tabs at the beginning of a line or paragraph into indentation that would be enough

**Comment by stevencohn** [comment]
There may be hope but will take me a couple of days to ponder.... err, um, find the time to ponder...

**Comment by 1001QAdotNET** [comment]
no rush... take your time

**Comment by stevencohn** [comment]
I'm giving up. :-( 
It quickly gets way more complicated than I want to deal with or think is worth the effort. It's not only an indentation but also forcing each line as a soft break (ctrl+enter) rather than a new paragraph (enter) in order to be able to collapse lines below, or "folding". 

OneNote is probably not the best tool for what you want to do. Reading code - any programming language - is best done in a programming editor, even something like Npp which has language-sensitive folding, syntax highlighting, etc. Or take a look at VSCode which is a proper mature development environment but still relatively light-weight

**Comment by 1001QAdotNET** [comment]
Ok I will see if I can handle it in Python
Again this is not for reading code
I need to be able to easily navigate content (IT books) highlight, collapse chapters or paragraps, add annotations and so on
Working with code snippets is the least that I need, for that I use Jupyter notebooks

**Comment by stevencohn** [comment]
Thanks for understanding. And yes, I see what you're doing now. But i's really non-trivial.

**Comment by 1001QAdotNET** [comment]
At some point I will have to put that Run a plugin option at work. 
I might begin with this but I might take a different approach ,  coming from the XML representation of a web page and injecting the OneMore XML back into an empty page
If that is something easier for you just go ahead and do it ...otherwise I will do it but it might be a while till get to that

There is certain docs where the OneNote  native copy and paste honors the source indentation ...I will have to see why and what  makes a difference and then try to find a quick and dirty way to user regex in Notepad++ to actually get  to something like that....it is all foggy but that is as much as I can see ahead in this direction

**Comment by stevencohn** [comment]
So the Paste RTF function doesn't work as you might expect. Since OneNote doesn't accept RTF, OneMore first converts it to XAML using a WPF control and then converts the XAML to HTML, pushes the HTML onto the clipboard, and then forces a paste. OneNote then knows how to transform the HTML to native OneNote XML. This was the easiest way to implement it without writing a massive RTF parser. 

If you can characterize which format does paste correctly into OneNote, I may be able to convert to that first and then insert it.

**Comment by 1001QAdotNET** [comment]
Take this page for example (a brutal example) 
https://lxml.de/apidoc/lxml.html.diff.html

Select the text in the left frame and copy that 
Try to paste that in OneNote in an empty page -using your RTF paste on any OneNote native method 
Press Ctrl+A (select all) and then Shift+Alt+1) -collapse all headings
Nothing will happen

Now open up Word and paste the content of the same page in Word
Select what you just pasted and copy
Paste that in OneNote on a blank page
Press Ctrl+A (select all) and then Shift+Alt+1) -collapse all headings
Everything gets collapsed (the page still needs work like remove empty lines or other things but you get the idea)

**Comment by stevencohn** [comment]
For HTML copied to the clipboard, I do have a solution that uses Word as a conversion engine. It seems to work for the lxml example you have above and a few others.

Of course, that requires Word to be installed on your system. Otherwise, if Word is not installed then it will fallback to what it does now. Give me a few days to play around with it.

On the plus side, I think I have a good solution for importing Word (and perhaps Powerpoint) files into a page too, closely preserving formatting

**Comment by 1001QAdotNET** [comment]
That is great news thank you!

**Comment by stevencohn** [comment]
Closing this ticket because it will be superseded by #88 and Advanced Paste RTF command
