### ISSUE TITLE
Improve MarkdownWriter

### ISSUE THREAD

**Issue by stevencohn** [stevencohn/OneMore#802]
* Try to handle nested tables
* Better detection of code blocks
* #978

**Comment by jasonjac2** [comment]
.... and do indented lists.   The markdown flattens indentation.

**Comment by stevencohn** [comment]
@jasonjac2 Can you give me an example? Because this:

<img width="257" alt="image" src="https://user-images.githubusercontent.com/9964757/208250784-e4c812bb-060b-46bc-9c4e-85cf004298c8.png">

should result in this:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/9964757/208250808-4f232e48-9cc1-4f42-871f-b89a507cb80c.png">

**Comment by stevencohn** [comment]
And this:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/9964757/208250881-0308c976-fbb2-4b2e-802c-8db50eba86c2.png">

will result in this:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/9964757/208250897-947789c1-bd51-4f7f-80e5-2c19928d46b9.png">

**Comment by jasonjac2** [comment]
Ah, I think it is because I don't use bullet lists normally, mine are like:
![image](https://user-images.githubusercontent.com/68282090/208251014-989c3443-c70a-4dae-b776-6a90fb73a6f5.png)
Results in: 
# JAC Work Unsorted Todo's
# Top 10  
Top level  
Level 2  
Level3  
Level 2  
Top Level


So I guess you could say it is doing it correctly, but maybe better to have an option (settings) to have implicit bullets based on indentation?

**Comment by stevencohn** [comment]
OK that is a problem then. It should add > and >> and >>> ... prefixes for indented paragraphs

**Comment by jasonjac2** [comment]
It seems to fail also:
![image](https://user-images.githubusercontent.com/68282090/208251261-cb033b33-39a4-42dc-8292-5474fed5f58f.png)
