### ISSUE TITLE
Add Outline Numeric Numbering to a Table

### ISSUE THREAD

**Issue by orangesnchocolate** [stevencohn/OneMore#811]
**Is your feature request related to a problem? Please describe.**
I like to use OneNote to track and manage tasks and to write SOPs. I use tables frequently, but not having outline numeric numbering is frustrating. Would you consider adding a function that would allow using the outline numeric numbering feature with tables, so that a numbering scheme like the one shown in the image could be produced?

**Describe the solution you'd like**
Creation of outline numeric numbering when using a table as shown in the image.

**Describe alternatives you've considered**
N/A

**Additional context**
Please see the image below. The numbering shown was produced using Word.

![example](https://user-images.githubusercontent.com/121527304/209742493-b42c6b88-d301-4110-903c-689327f9ca81.jpg)

**Comment by stevencohn** [comment]
OneMore already has a fill-down command for tables that can auto-increment and fill cells based on a starting value. So this is easy to do. 

The difficultly I'm having is envisioning how best to detect levels.... happy to take suggestions :-)

**Comment by orangesnchocolate** [comment]
In Word, the process of assigning Styles and Levels is manual, but there are some options to make it faster.

In Word, when you assign a Style to text, you can ‘adjust’ levels by using the indent function. So, once the Style is assigned, Word ‘remembers’ the numbering scheme and carries that scheme forward. There is also an Add On from BEC LegalBar that makes using the Style feature in Word easier: https://www.beclegal.com/solutions/document-automation/legalbar/. In the photo below, see the 1, 2, 3, 4, etc.—clicking on those buttons allows you to manually assign the style and the level. Word also allows you to assign a Shortcut Key to the Styles.

![image](https://user-images.githubusercontent.com/121527304/211895893-1c8db21b-e055-417f-a1b4-631c4cd8cfc5.png)

In Word, you can also tie the Style to the Level, but the user must initially assign the Style (and, if linked, the Level is also assigned). Word also has this concept of “Style for following paragraph”, so that when you hit return, the Style you identified to follow is used without you having to assign the Style manually again. See screen captures below.

![image](https://user-images.githubusercontent.com/121527304/211895947-1806506b-75eb-4bb7-a841-a2b74205b815.png)

![image](https://user-images.githubusercontent.com/121527304/211896293-7c00ef98-e730-42ac-a020-451f55eb4ca4.png)

**Comment by stevencohn** [comment]
So thinking of an end-to-end workflow...

1. Create new custom styles for every level that you might have in a table. You could update existing styles but I'm guessing new styles might be a better approach
2. Fill out the table, possibly using the Fill-Down command to auto-increment, although multiple levels of decimal values would be mostly manual
3. Apply the level-specific styles to each of the cells. Some consecutive rows could be treated together by selected them all at once.
4. Run an "Indent" command to appropriately indent each cell according to the applied style. (The apply-style command in step 3 cannot automate the indent because some users may want to reuse a style elsewhere where an actual indent doesn't make sense; regardless, it would get very complicated and confusing.)

This is quite a lot of effort in my opinion. I'm still failing to see the benefit here over what you can already do.
