### ISSUE TITLE
More Functionality for Quick Note

### ISSUE THREAD

**Issue by JRPX33** [stevencohn/OneMore#860]
Get it, "More" Functionality? :-)

This is kind of multiple requests.... so forgive that... but I'm not quite sure how it would be implemented so I kept it together.

I use the QuickNote feature of OneNote a LOT as I work throughout the day.  Having it in the system tray is amazing because no matter what I've got on the screen, I'm one click away from a new note.   I use this mostly just capturing screenshots, random thoughts, pages from websites, etc.    It's basically my short term memory holder, so getting stuff in very quickly is critical.

However, I've found this leads to a big jumbled mess in my QuickNote section over time.   And what's worse, none of those pages have titles or times like normal pages, so they're even more unorganized.  (All the research I've seen said QuickNotes can't have a custom template or even a normal page).

I would love to have functionality such that the QuickNote would have more functionality.   The big things are:

1) Use a normal OneNote page with title and date -- or even a custom page.
2) Be able to pick which notebook/section the note goes into.

For #2 I could see this as either multiple QuickNote icons in the system tray, or even better, clicking on the system tray bringing up a dialog giving me a list of preselected notebooks/sections that I would want to add this to.

I've looked into all sorts of ways of accomplishing this with PowerShell, VBS, shortcuts, etc.... but none of them seem to work out right, so really curious to see your thoughts on this.

**Comment by stevencohn** [comment]
There's nothing particularly special internally about a QuickNote. I'm guessing Microsoft's intent is that they are really intended to be exactly that - very quick and small thoughts to jot down. So adding lots of fluff like titles, timestamps, and OMG page templates is way too much faff.

Having said that, it would be quite simple to add a command to scan and catalog all quick notes:
* Base on a #keyword in the note, move them to a specified notebook/section (any user-based directives like this are always tricky because of the huge amount of error detection needed!)
* When moved, add a page title showing the original time stamp. The title would best be blank - in which case, OneNote shows the first few words of content in the Pages panel. Alternatively, I could set the title to the first few words

**Comment by stevencohn** [comment]
Other thoughts...
* collating quick notes into a single note, or grouped by day/week/month

**Comment by jasonjac2** [comment]
I use office lens a lot from my Android phone and wish it would auto group pages for me and maintain a ToC page.

**Comment by JRPX33** [comment]
I like what you're thinking... it's not as fancy as a popup, but obviously easier to code so I can live with that :-)

My suggestion for the title would be the first line of text in the note.  This is actually how OneNOte handles this already.  When you see a page in a notebook that started life as a quicknote, it shows the first line of text as the title of the page in the list of pages.

Maybe "the way" here is putting all my destinations into snippets.    Then if I can't remember the exact name I used for the #keyword it'd be there.    

I'm happy to test if you decide to do this!

**Comment by stevencohn** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/9964757/218269516-74393948-9592-4dee-b3e4-adc7355a47c5.png">

**Comment by julie777** [comment]
@JRPX33 

> However, I've found this leads to a big jumbled mess in my QuickNote section over time. And what's worse, none of those pages have titles or times like normal pages, so they're even more unorganized. (All the research I've seen said QuickNotes can't have a custom template or even a normal page).
> 


> I would love to have functionality such that the QuickNote would have more functionality. The big things are:
> 
>     1. Use a normal OneNote page with title and date -- or even a custom page.

I also use quick notes, but rather than the button I open a new quick note with `<win>-n` and in OneNote/options/Display I check the box to "dock new quicknote to the side of the desktop" which does what it says. In addition it temporarily shrinks the active window to make space, and changes it back to normal when I close the quick note.
This lets me still see what I was previously looking at while making a note. 

The docked quicknote window creates a new page and the cursor starts in the title field. 
This is what I see when I open a quick note. (sorry that it is so large)

![image](https://user-images.githubusercontent.com/5090005/218356394-b8e4b2c5-3124-45bf-a67f-001719e41cf7.png)

I guess that I should mention that I am running Windows 10 and using Office 365 OneNote.

> 
>     2. Be able to pick which notebook/section the note goes into.

I have a special section that I created in my main notebook just to act as an inbox where I often just add some information, a link, etc. quickly without having to decide where it really belongs. I have that section set as the location for quick notes. The quick notes all have titles and are easy to move when I process my inbox. 

Sadly, I don't currently have something that reminds me to clear my inbox. :-)
