### ISSUE TITLE
Update install fails with process "com surrogate"

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#892]
**Describe the bug**
Every time there is a new OneMore version and I choose update from the dialog that notifies me of the update the install fails because there is a process running and blocking the install.

**To Reproduce**
1. Open OneNote where there is a new update available
2. a OneMore dialog opens with notification of the update
3. confirm that I want to install the update
4. OneNote is closed by the install process
5. a dialog pops up saying that install can't proceed because of "com surrogate" and has choices to try again and cancel
6. I open task manager and kill the "com surrogate" process (thankfully the PID was in the dialog) and hope that ending the process won't cause any problems
7. I select try again and the install completes

**Expected behavior**
I expect the install to just work

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: O365,  64bit
 - OneMore Version 5.6.0 but the problem has been happening with each new version for some time now

**Additional context**

I hope this is the correct part of the log:

26972:1] Starting dllhost 26972, CPU=2904Mhz, en-US/en-US, v5.5.0, OneNote 15.0, Office 16.0
26972:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16026.20146)
26972:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
26972:1] ..OneAddInsUpdate(custom[])
26972:1] ..building ribbon
26972:1] ..building ribbon colorizer commands
26972:1] ..building ribbon groups
26972:1] ..building context menu
26972:1] ..OnStartupComplete(custom[])
26972:1] ..starting command service
26972:1] ..starting reminder service
26972:1] ..ready
26972:5] defining 146 hotkeys for input locale 1033
26972:6] Running command UpdateCommand
26972:3] ..downloading MSI from https://github.com/stevencohn/OneMore/releases/download/5.6.0/OneMore_5.6.0_Setupx64.msi
26972:14] ..creating install script C:\Users\julie\AppData\Local\Temp\OneMoreInstaller.bat
26972:14] ..starting installation process

27108:1] Starting dllhost 27108, CPU=2904Mhz, en-US/en-US, v5.6.0, OneNote 15.0, Office 16.0
27108:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16026.20146)
27108:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
27108:1] ..OneAddInsUpdate(custom[])
27108:1] ..building ribbon
27108:1] ..building ribbon colorizer commands
27108:1] ..building ribbon groups
27108:1] ..building context menu
27108:1] ..OnStartupComplete(custom[])
27108:1] ..starting command service
27108:1] ..starting reminder service
27108:1] ..ready
27108:5] defining 147 hotkeys for input locale 1033
27108:9] Running command UpdateCommand
27108:9] Running command AboutCommand

**Comment by stevencohn** [comment]
Actually just figure out a way to fix this over this past weekend. So hopefully should have something together for v.Next.  Of course, upgrading from 5.7 or a previous version to v.Next may still be a problem but v.Next to v.Next+1 will hopefully work.

**Comment by stevencohn** [comment]
Also see #642

**Comment by jasonjac2** [comment]
+1 on this.  I have this, but i also have GEM & OneTastic installed.  I goto task manager and kill the process - I can't detect any instability.  Install then works fine.

**Comment by stevencohn** [comment]
I thought I had a bright idea. But alas... this will have to wait until the new installer. I'll see if I can add a page to this installer telling the user to manually shut down OneNote because the it cannot. The COM Surrogate message happens in the MSI before I can intervene. One of the many reasons I need a new installer framework like WiX

**Comment by Merryannp** [comment]
I just attempted to install the latest update and this may be the same bug. Didn't copy the entire log, just the part that seemed relevant

14192:7] Running command UpdateCommand
14192:15] Error running command UpdateCommand
14192:15] System.ComponentModel.Win32Exception
Message: The process cannot access the file because it is being used by another process
Source: System
StackTrace:    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at River.OneMoreAddIn.Commands.Tools.Updater.Updater.<Update>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.Commands.UpdateCommand.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__5.MoveNext()
TargetSite: [System] System.Diagnostics.Process::StartWithShellExecuteEx()

**Comment by stevencohn** [comment]
_Release note_ - update the docs to explain that this is fixed in the internal Update command but will not be fixed when running the installer standalone outside of a running instance of OneNote.

**Comment by Merryannp** [comment]
Steven,

Sorry, but OneMore is still causing me problems. I'm attaching my log file, which I haven't deleted for a while. It should give you all of the info you need. Since I don't try to update OneMore without an update notification, OneNote is definitely running when the update is activated.  One thing that does seem to have been fixed is that OneNote isn't crashing after the update fails.

BTW - I just love this little app (I do realize it's actually not that little). Any chance of a macro group for creating subsections, subsection groups, subpages and subpage groups? I do a lot of genealogy, the family cookbook and crochet pattern collection. I'm using these all the time & constantly forgetting how to do them. Hey - I'm 71 & retired IT for 20 yrs. I'm entitled to forget some things!

Thanks!!

Merryann Palmer
________________________________

**Comment by stevencohn** [comment]
@Merryannp  Please see the comment in the [5.7.2 release notes](https://github.com/stevencohn/OneMore/releases/tag/5.7.2)

Where is says:

> Note that this will only apply when updating from 5.7.2 to a later version; you must still terminate OneNote and its dllhost process before running the installer to update to this version

**Comment by stevencohn** [comment]
And I LOVE how your using OneNote. Age doesn't matter [he says as he gets older-by-the-day]

What are you suggestions regarding how to make "grouping" easier than OneNote already provides?

**Comment by Merryannp** [comment]
Dang. I missed that. I'll let you know in a few minutes.

________________________________

**Comment by Merryannp** [comment]
The 'make a subsection' and 'make a new subsection group' is easy enough - until I forget it makes a new layer instead of one of the same layer , which is really what I want. It does get confusing at times. Then I can't seem to find a way to promote a sub to a higher level. Just having all of the commands in one place would be a big help. I guess I think MicroSoft should have made it like outlining in Word - tab in gets you a child level, tab out promotes to a parent level. My biggest problem with OneNote was switching from EverNote and using the import tool. It made notebooks out of all my sections and created a mess that I'm still straightening out 2 years later.

I always liked to use the WYSIWYG macro builder in Word - I didn't have to learn the code. I wouldn't mind trying to do some macros on OneNote, I just don't know where to start. And I was one of the "idiots" who learned DOS on a TRS80-Model 1, then Cobal to get reports out of a mainframe database. When I retired, I couldn't have qualified for my own job - I didn't have the college degree. Enough of this.

I downloaded the updated version of OneMore. Looks great. I doubt if there will be any more problems with it. Thank you. I really have to pay more attention to detail.

Thanks again, Steve

Merryann
________________________________

**Comment by stevenmcohn** [comment]
I think the confusion - which is shared by many - is that Microsoft didn't stick to the "notebook" paradigm when naming all of the little things in OneNote, section groups being the worst example.

Just like a real notebook, OneNote notebooks have sections, sections have pages. Section Groups are folders of sections, nothing more. 

So if you end up with a number of sections under a section group and want to move them up a level, you can drag-drop them to the parent group - or the notebook itself if they are already in a first-level group. And if the group is empty, right-click and delete it. It's easy if you "pin" the notebook pane so you can see the full hierarchy and manage it (pic below)

I'm not sure OneMore can make that much easier.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/74603828/220390951-cec205a7-3442-44e5-b43a-c91f369db100.png">

**Comment by stevencohn** [comment]
I think the confusion - which is shared by many - is that Microsoft didn't stick to the "notebook" paradigm when naming all of the little things in OneNote, section groups being the worst example.

Just like a real notebook, OneNote notebooks have sections, sections have pages. Section Groups are folders of sections, nothing more. 

So if you end up with a number of sections under a section group and want to move them up a level, you can drag-drop them to the parent group - or the notebook itself if they are already in a first-level group. And if the group is empty, right-click and delete it. It's easy if you "pin" the notebook pane so you can see the full hierarchy and manage it (pic below)

I'm not sure OneMore can make that much easier.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/74603828/220390951-cec205a7-3442-44e5-b43a-c91f369db100.png">

**Comment by Merryannp** [comment]
Steven - sorry to attach this to this old problem, but I couldn't find any other way to contact you. I just got a new laptop with Win 11, and every time I try to download the .msi installer, it tells me that that type of file is not normally downloaded and stops the download. I've tried every way I know of to download the x64 file, and the closest I've gotten is something Windows renamed to something I've never heard of & it wouldn't let me rename either. Unfortunately, I deleted it several hours ago. So - how do I get the installer if Windows won't download it? It is most frustrating.

Thank you so much,
Merryann Palmer
Ionia, Michigan

________________________________

**Comment by stevencohn** [comment]
Windows does make it difficult on purpose to protect users from software with potential viruses. In this case, it's because the installer is not digitally signed - something that I would need to pay a couple of hundred dollars to do. But you can get past it.

When you start the download you may see something like this.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/9964757/228207442-7baabe8a-fbef-410c-a525-3292d1c7baa0.png">

Click the three dots to expand it and choose Keep

<img width="244" alt="image" src="https://user-images.githubusercontent.com/9964757/228207562-757e9e93-df5d-431b-ba26-48cb21027abd.png">

Now click Show More

<img width="274" alt="image" src="https://user-images.githubusercontent.com/9964757/228207663-e28ee0d7-aff1-4892-8d40-bdeab524bab6.png">

And click Keep Anyway

<img width="267" alt="image" src="https://user-images.githubusercontent.com/9964757/228207798-4461303e-abb4-4968-b876-1b8bb8781ccb.png">

The file should be in your Downloads folder. Right-click the file and choose Properties and then tick the Unblock box:

<img width="269" alt="image" src="https://user-images.githubusercontent.com/9964757/228208036-cf5c4225-7451-44fd-9eb1-11c4e4839e32.png">

Now you should be able to double-click the file to run it.

**Comment by Merryannp** [comment]
Thank you so much. I really think I'm getting past my use by date on some of this stuff. But, like the kitten hanging from the tree branch, I haven't quite given up yet!

Merryann
________________________________

**Comment by julie777** [comment]
I haven't had any problems with the last couple updates.
