### ISSUE TITLE
XML editor - Update Page button remains disabled after changes are made

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#897]
**Describe the bug**

When viewing XML the Update Page button is disabled. However, when I actually change the XML content the button remains disabled.

**To Reproduce**
1. Open OneMore XML page view
2. put cursor in a CDATA text string
3. type some additional text
4. Update Page is still disabled

**Expected behavior**

The Update Page button should be enabled/disabled based on the state of the XML content

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: O365 64bit
 - OneMore Version: 

**Additional context**

I also tried changing a font size and the Update Page button remained disabled.

**Comment by stevencohn** [comment]
Sorry, I refuse to remove the safe-guards. I will guarantee, through tight controls, that the user must jump through hoops to actually submit changes to the page XML. I've considered adding a warning box when you click the OK button but I do not believe that is sufficient. This dialog requires that you explicitly acknowledge the risk by enabling the checkbox at the top.

There may be better wording or flow.... I'll think about it.

**Comment by julie777** [comment]
@stevencohn  
Sorry. I looked at the checkboxes but for some reason the part in parens didn't click. 

I do think that if somehow Update Page and Cancel were clear and Close never saved then it would be pretty safe regardless. If the only was to save is to Update Page then there is an explicit action required.

Thinking about this, I did start considering editing to change formatting for readability vs changing actual XML content. I wonder if you are differentiating or if that is part of the need to use the checkbox.

**Comment by stevencohn** [comment]
It may be more clear if editing was disabling until that checkbox is ticked - and renaming that checkbox to simply "Enable editing".

That checkbox evolved this way because I originally wanted to hide all the "noisy" attributes while I was trying to debug the actual content. The checkbox would turn on things like the ID attribute, which are also needed before submitting changes to a page. So it became dual purpose. I understand how it can be confusing not knowing the history. I'll rename the checkbox.
