### ISSUE TITLE
Favorite: what is final version?

### ISSUE THREAD

**Issue by valuex** [stevencohn/OneMore#908]
# New Feature/Solution
Glad to know the new feature to index the **Favorite** by inputing several chars.  
And previously several threads has talked about the **Favorite** feature, #900 , #902 and #658 (#658#issue-1402292039).   
My idea about **Favorite** looks like a quick launchers, such as WOX, Flow Launcher, Alfred.
More specifically, 
* users can type few letters to quickly filter out the desired page/section/notebook and click or press enter to visit it.
* the search algorithm supports regex, and the user can set different regex mode, like input ```ab```
  - simple regex: ```*.ab.*```, matches the consecutive combination
  - full regex: ```*.a*.b*. ```, matches the non- consecutive combination
* support indexing by the first letter of Chinese Pinyin
* As for the **Favorite** feature, it can be kept now and has its own area for displaying the indexing results.
* From the long-term point of view, I think it can also be dropped, because the searching and sorting algorithm is good enough, acting like good launchers, considering 
  - the recently visited page, 
  - how many times one page has been visited (can be recorded in the xml of the page)
  - record the user  input chars and corresponding visited pages (this feature can be used to replace the current nickname of a favorite page)
  - pressing ctrl+1/2/.../9 to quickly navigate to the top 9 indexed items

![image](https://user-images.githubusercontent.com/3627812/218747132-c52ddfff-260a-4d7a-b6b2-0aefb109d096.png)

## Why hope to re-invent the wheel of ```Moving/Copy page to```
Because the internal function does not support regex indexing, neither indexing by first letter of Chinese Pinyin

**Comment by stevencohn** [comment]
The latest iteration of the Favorites dialog (Alt+F) that will be released as part of 5.7.1, should be sufficient for the vast majority of users. It allows simple substring search. Regex search is far too complicated for any non-programmers for such a simple function.

The [Quick Filing Dialog Box](https://learn.microsoft.com/en-us/office/client-developer/onenote/quick-filing-dialog-box-interfaces-onenote?redirectedfrom=MSDN) is a built-in part of OneNote. This is the dialog that powers the Move/Copy functionality in both OneNote and OneMore. To recreate this dialog just to add a Favorites node is not economical. Regex capabilities for a global search would require its own search engine since the built-in Windows Search does not support regular expressions.

**Comment by julie777** [comment]
I love the new version's ability to get to my page with only a couple keystrokes.

One of the big benefits is being able to jump to the page and quickly add something and then jump back without interrupting my current task. 

This is much better for me in many cases than quick notes which I also use. With quick notes I have to find time to review them and file them correctly.

**Comment by julie777** [comment]
@valuex 
>> My idea about Favorite looks like a quick launchers, such as WOX, Flow Launcher, Alfred.

My idea was similar, based on my constant usage of `<win>` then type a few chars and hit enter to run the app. I also found that the Gmail approach of (g)oto (l)abel then type and hit enter to select the label is extremely efficient.

With a quick select/jump mechanism I think the need to sort or manually order list items goes away. I don't even really look at the new dialog for favorites that pops up. I just `<alt>-f fe <enter>` and it opens my page in OneNote so that I can record feedback that I want to leave for some product.

Attaboy to @stevencohn
