### ISSUE TITLE
Create an online notebook visible per Feature or Bug request so we can send you samples 

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#91]
**Is your feature request related to a problem? Please describe.**
If I need to submit a request for a feature or a bug I would like to be able to send you an example

**Describe the solution you'd like**
That could be an XML doc but it could also be a "Select text", Right click and 'Create a new page' in a notebook that OneMore can access online and send the content that is the object of the bug request of feature request there.
When done return a link to the content

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

THE FINE PRINT
This is a hobby project that I started for myself. I'm happy to take requests and will promise to consider each one carefully but offer no guarantees that I will ultimately agree to their usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
If this was a bigger project with a bigger team and we expected an in-flood of requests and defects from all directions then it would be worth investing in something like this. For now, I'm going to focus on new features (and new bugs) rather than worry about there being a slew of existing issues.

Honestly, as far as I can tell, there is a grand total of about three people using this. But that was never my goal. It was always "something for me" first. :-)

**Comment by CLITrees** [comment]
understood ...that is OK then ... Indeed there is not lots of issues/bugs. Keep it in mind if it gets to that level.

**Comment by 1001QAdotNET** [comment]
understood ...that is OK then ... Indeed there is not lots of issues/bugs. Keep it in mind if it gets to that level.
