### ISSUE TITLE
XML viewer is modal and prevents watching the effect of page changes

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#916]
# Problem to Solve

I have to close and reopen the XML view constantly while trying to understand why formatting isn't working.

# New Feature/Solution

I hate to refer to another add-in, but Onetastic has a better implementation of XML view which is non-modal and can auto-refresh. That is what I want.

**Comment by stevencohn** [comment]
I believe the Onetastic approach is a mistake, IMO. I more apt to remove the Update button than I am to make the XML Dialog a full-blown interactive editor. It's intent is as a diagnostic tool, not a development tool. The risk is way too high to users (who are not named Steven or Julie)

**Comment by stevencohn** [comment]
Back to the philosophy of OneMore, that differentiates it from Onetastic, it is intended to enhance the OneNote experience for all users. Onetastic is great, but hard to crack for non-programmers. 

I debated ever releasing the Xml Dialog. But I, as the OneMore developer, found it useful to understand how OneMore works. And I wanted to lift the covers a little bit for those who were curious to understand the inner workings of OneNote. It was never intended to be an alternative way to update content. I want to stay true to the vision and philosophy. I hope that makes sense.

**Comment by julie777** [comment]
I am in complete agreement with you Steven, about OneMore vs Onetastic. 

However, I would be happier if the XML tool better supported inspection and diagnostics even if it meant removing the edit feature. :-)

**Comment by stevencohn** [comment]
If you really think you need it then extracting it to its own app might be the easiest solution to get what you want. The reason I say that is more of a technical discussion than a philosophical one. OneNote addins run in dllhost.exe processes, to isolate any bad behavior from the main ONENOTE.EXE process. The addin runs in an MTA model. There are often times when OneMore needs to thunk down to an STA model to make things work. Keeping it all async and interoperable across these boundaries makes an interactive dialog, running in-process in the dllhost, actually more complicated than it should be. So for example, if you make a change in the dialog, don't expect to see the change reflected in OneNote until the dialog is closed, unless you run the dialog is in a separate thread with its own UI message pump. Auto-refresh is another problem because the .NET Interop assemblies don't have eventing. I imagine Onetastic might be using the native DLLs here to take advantage of that (the eventing capabilities are not as excited or useful as you might think because navigation and page update is just about the only events that are exposed.)

Anyway, I still maintain that it's a long-pull for a short-term gain. You'll make better use of your time simply learning the XSD schema and poking around the OneMore Command implementations.

Styles are quite simple. Once you "get it", it's not that hard. I will dedicate some time in the next couple of days to writing up an article.

I also maintain that, as is, it's probably just as efficient as far as clicks and keystrokes. I often edit a page, press Ctrl+Alt+Shift+X to open the Xml dialog to see what happened, press Esc to close it. Repeat. That's not so hard to me. The key is to break down your problem is a small example so you're not scrolling around the dialog to find your context.
