### ISSUE TITLE
Add an option to set the default font and size used for formatting code

### ISSUE THREAD

**Issue by jiahe224** [stevencohn/OneMore#925]
# New Feature/Solution

Add an option to set the default font and size used for formatting code. My OneNote default font is Microsoft Yahei, this font is not very clear and concise for the code.

**Comment by stevenmcohn** [comment]
Hi @jiahe224. You can set the default font and size in the OneNote Options.

Click File, then Options, then the General tab. You'll see a section "Default font" where you can set the font, size, and color.

**Comment by stevencohn** [comment]
Hi @jiahe224. You can set the default font and size in the OneNote Options.

Click File, then Options, then the General tab. You'll see a section "Default font" where you can set the font, size, and color.

**Comment by jiahe224** [comment]
@stevencohn My native language is Chinese, so the default font of my OneNote is Microsoft Yahei, because it displays Chinese well, but for the code, Microsoft Yahei is not very good, so I want to use the Western font for the code alone.

**Comment by stevencohn** [comment]
Sorry that I closed this by accident (I do that too often to be honest)

You want to format code using a different font than your default language character set. This is one of the reason why OneMore has the feature to create custom styles. From the [My Styles menu](https://onedrive.live.com/redir?resid=6925D0374517D4B4%2158723&authkey=%21AN6SD9aiIbjQLi0&page=View&wd=target%28Commands.one%7Cdefb70f1-1b5e-4ca1-95db-a5227b84d8de%2FMy%20Styles%20Commands%7C5c8ace54-e8ea-44aa-9fe5-4e957b96a683%2F%29&wdorigin=703) (previously named _Custom Styles_) you can modify the provided "code" style or create your own using any font you find appropriate.

The main reason why OneMore has the My Styles feature is because it is not possible to change the built-in OneNote styles.

**Comment by jiahe224** [comment]
@stevencohn Thank you very much, I found the setting, but it feels a bit convenient. For the code, if you want both syntax highlighting and font style, you need to set it twice. Can you change the font while syntax highlighting like gem or NoteHighlight?

**Comment by stevencohn** [comment]
Not everyone will want that. It would require an option, a setting, more management UI.... not that it can't be done, but needs prioritizing.

**Comment by jiahe224** [comment]
Yes, this is a low priority requirement. Also there is a bug that sometimes using styles causes the font on the page to become larger, see the gif for details. The default size of my code style is 11, but after using it all the fonts on the page become 14.
[https://drive.google.com/file/d/1CI_M8TT-LSRMIxsTjaJlWHGbxo7wVZUk/view?usp=sharing](url)
