### ISSUE TITLE
Notion-esque, web iframe?

### ISSUE THREAD

**Issue by SmartBoy84** [stevencohn/OneMore#946]
When pasting youtube links, I've noticed that onenote is able to automatically add an iframe for the youtube video to the page
Would it be possible to allow for other websites to be shown in a similar manner?

**Comment by stevencohn** [comment]
It's not actually an iframe but rather special embedded media content recognized by OneNote. [This Microsoft article](https://support.microsoft.com/en-us/office/embed-content-in-onenote-fd5abf7d-abd4-4902-8e5f-93088c45b11d) lists out all the supported sites and services.

OneNote handles this internally when you paste a link from one of those sites. Since it is not an iframe, and it is internal functionality that I don't have access to through the interop API, this is not an extensible feature.
